### ISSUE TITLE
Looking forward to nCore support!

### ISSUE THREAD

**Issue by gurabli** [cardigann/cardigann#1]
First of all, great idea and I'm very glad you started this project (I like and use Jackett a lot, but hate mono too).

If you can port nCore tracker, I'm here to help in testing! Just let me know what you need from me to implement nCore and I'm here to help & test.

**Comment by lxt2** [comment]
Absolutely! I could either walk you through the process of creating a new definition (which is fairly straight forward if you understand css selectors), or if you wanted to send me an invite to the tracker I'll add it.

**Comment by gurabli** [comment]
Sounds really great! I'm afraid I don't know how to add new definitions, but I'm glad to send you an invite and help you with the site structure, testing, etc. 

Send me an e-mail to gurabli at gmail dot com and let me know the e-mail address where I should send you the invite!

BTW: do you have any instructions how to install Cardigann on Ubuntu Server 16.04, and a systemd service file for it? Apart from not using mono (which is great) what is the difference between Cardigann and Jackett? Do we get all the functions we have in Jackett (and even more)?

Thanks!

**Comment by lxt2** [comment]
I emailed you @gurabli. In terms of installing on Ubuntu / systemd, it should literally be a case of downloading the binary from the releases (https://github.com/cardigann/cardigann/releases/download/v1.1.1/cardigann-linux-amd64) and then creating a systemd definition for it. I need to document this (#3), for now follow (#2) and I'll post systemd files there.

**Comment by gurabli** [comment]
Just wanted to follow up on nCore support? Let me know if I can help you.

**Comment by lxt2** [comment]
Trying to translate Hungarian was interesting, and there were a lot of strange quirks with this tracker, but it's done. Let me know how you go @gurabli.

**Comment by gurabli** [comment]
Many thanks @lxt2 
I downloaded the latest version to test it but the def doesn't contain nCore yet. If you add it, I will certainly test it and report back!

The site stuff promised English for a very long time but still nothing. You could have contacted me anytime for translation help:)
The site has some strange way of solving things, but it is really a great tracker. I'm sure lot of people will appreciate your work.

**Comment by lxt2** [comment]
Are you sure, I can see it? `definitions/ncore.yml`. 

Which release are you looking at? Check https://github.com/cardigann/cardigann/releases/tag/v1.3.0

**Comment by gurabli** [comment]
I guess when I checked it was not available yet. It was there indeed when I checked your link. I had just a little time, but I tested with Sonarr and to me it looks everything is working really nice. I will make Cardigann now the default Indexer and use it on longer term. Excellent work, very appreciated!
