### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by seertenedos** [cardigann/cardigann#10]
It would be great to see your app in a docker container! Maybe http://tools.linuxserver.io/dockers would even do it for you if you asked them.

**Comment by lxt2** [comment]
Compiled binaries make this pretty easy: https://github.com/cardigann/cardigann/blob/master/Dockerfile

Getting automated builds into dockerhub might be slightly harder. I will investigate at some point.

**Comment by seertenedos** [comment]
i have used http://wercker.com/ for that before on their free plan.  maybe that would suit.

**Comment by lxt2** [comment]
This is now a thing: https://hub.docker.com/r/cardigann/cardigann/

**Comment by seertenedos** [comment]
Just checked out the docker file. I think there should be a volume for the json file. You need to keep the config outside the container so that you don't loose the config on container updates. I still plan to install it to have a play.  everything else looked good

**Comment by seertenedos** [comment]
also got an error trying to start the docker container "Not Found ("Container command '/cardigann' not found or does not exist.")" when using the following create statement
docker create \
    --name=cardigann \
    -p 5060:5060 \
    cardigann/cardigann:latest

**Comment by lxt2** [comment]
Ah yup, you are correct. Thanks.

**Comment by lxt2** [comment]
I've re-opened this to track progress.

**Comment by lxt2** [comment]
I believe this should be working now, are you able to try it @seertenedos?

**Comment by seertenedos** [comment]
Yea just tested it and it seems to be working correctly now!
