### ISSUE TITLE
Indexer Request: SceneAccess

### ISSUE THREAD

**Issue by savahu** [cardigann/cardigann#101]
url: http://sceneaccess.eu
Currently open signup, first time in 10 years :)

**Comment by lxt2** [comment]
I had a look, couldn't see a signup link.

**Comment by mmarquezs** [comment]
I did this one already I will check a couple of things and I will do a pull request.

**Comment by mmarquezs** [comment]
I just did the pullrequest: https://github.com/cardigann/cardigann/pull/106
