### ISSUE TITLE
Where to find new definitions

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#102]
I update cardigann with cardigann
cardigann update --channel=edge

but how to keep up with the definitions available? Are the also published somewhere or can I retrieve them with the update?

**Comment by lxt2** [comment]
Since 1.7.0 the definitions are baked into the binary, so you get them when you update! You can click on the title of the indexer and it will tell you what version of the definition you have.

**Comment by aroundmyroom** [comment]
aahh wauw !! thanks .. !!
