### ISSUE TITLE
Cardigan search results are plain-text vs links for native sonarr and jackett results

### ISSUE THREAD

**Issue by zductiv** [cardigann/cardigann#103]
### Description of feature/enhancement
Sonarr and Jackett search results in manual search in Sonarr are links that take you directly to the page on the tracker. This is helpful because you can check comments and other information provided by the uploader. On cardigann, they are only plain-text so you have to go to the tracker yourself to find the comments and other information.
### Justification
Just is a nice to have.
### Example use case
![image](https://cloud.githubusercontent.com/assets/8939440/19300554/8654b41a-908d-11e6-9cf0-aa042717a7a6.png)
in the attached. thePirateBay links are returned from jackett.
eztv and tpb-c are from cardigann.

**Comment by lxt2** [comment]
Interesting, I wonder which field it's using for that.

**Comment by theCheek** [comment]
i think this is a dupliate of #64

**Comment by kaso17** [comment]
It's the "comments" field.
most definitions don't set it, they set only the details field.
On my latest definitions I set only the comments field.
The details field doesn't seem to be used for anything but the GUID.
If you just change the details field for all trackers to comments it should fix the problem.

**Comment by lxt2** [comment]
Ooops, looks like I misunderstood #64, apologies @theCheek. I've pushed up a fix that uses details for comments unless a specific comments field is provided.

**Comment by lxt2** [comment]
This made it into the 1.8.6 release.
