### ISSUE TITLE
Indexer Request: Sceneaccess

### ISSUE THREAD

**Issue by manderss99** [cardigann/cardigann#107]
### Indexer Name
sceneaccess

### Is the indexer private or public? If private, can you provide an invite?
private, I have invite

### Indexer URL
https://sceneaccess.eu

### Indexer language
English

**Comment by mmarquezs** [comment]
Already requested here: https://github.com/cardigann/cardigann/issues/101 and already done: https://github.com/cardigann/cardigann/pull/106 . Waiting for the pull request to be merged.
