### ISSUE TITLE
Correnct Demonoid url to "http://dnoid.me/"

### ISSUE THREAD

**Issue by fkick** [cardigann/cardigann#109]
Hi,

When attempting to use the demonoid indexer, I get the error users can get the error

`Failed to match selector "a.user img"`

This is because they've moved from "http://demonoid.cc" to "http://dnoid.me"

**Comment by lxt2** [comment]
https://github.com/cardigann/cardigann/commit/006342f32492db8508b07c502b1984d304e2c809

**Comment by lxt2** [comment]
Update to the latest edge for this fix. https://github.com/cardigann/cardigann#updating

**Comment by vinchi007** [comment]
Not working:
`cardigann test-definition src/github.com/cardigann/cardigann/definitions/demonoid.yml
→ Testing 1 definition(s) (dev/freebsd/amd64)
→ Testing indexer demonoid at http://www.dnoid.me/
  Testing required config is available FAILURE ✗ in 12.521µs
→ Indexer demonoid FAILED with No value for demonoid.username in config
cardigann: error: One or more tests failed, try --help
`
