### ISSUE TITLE
Indexer Request: TtN

### ISSUE THREAD

**Issue by Matttter** [cardigann/cardigann#112]
### Indexer Name

TtN
### Is the indexer private or public? If private, can you provide an invite?

Private, it works with jackett ( https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/TransmitheNet.cs ) so it should be possible to port from there? If that doesn't work out I can surely arrange an invite
### Indexer URL

transmithe.net
### Indexer language

English

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com and I'll add it

**Comment by kaso17** [comment]
Got the invite, thank you.
I'll publish the definition soon.

**Comment by kaso17** [comment]
done, for now you've to install the definition manually until @lxt2 has time to do a release again.

**Comment by Matttter** [comment]
Oh weird I didn't get you an invite, someone else must've found this? Well doesn't matter, thanks a lot!
