### ISSUE TITLE
Feature request: Allow proxy through Privoxy+Tor

### ISSUE THREAD

**Issue by AndyPeepsJR** [cardigann/cardigann#115]
### Description of feature/enhancement
Basically, I want to be able to redirect all, or some, through Privoxy , so it can pass on the requests to Tor, especially for ThePirateBay, that has a .onion presence.

### Justification
Access restrictions in my country

### Example use case
To access websites that are inaccessible in a particular country.

**Comment by lxt2** [comment]
Adding the ability to use an HTTP proxy would be pretty trivial, I'd have to look into the Tor side of things, suspect that would be more involved.

**Comment by AndyPeepsJR** [comment]
Actually, for anyone in a similar position as myself, being able to assign a proxy would be enough, as I use Privoxy to switch traffic appropriately between normal traffic and tor routed traffic.

**Comment by lxt2** [comment]
Setting `HTTP_PROXY` should actually already work, but I will add more explicit support for it.

**Comment by lxt2** [comment]
https://github.com/cardigann/cardigann#using-with-a-proxy

**Comment by AndyPeepsJR** [comment]
Sorry, but is this an update, and any advice how to do this in the Linux environment when running it as a service? Could you update that section in the README appropriately.

Thank you.
