### ISSUE TITLE
Indexer Request: HD Space

### ISSUE THREAD

**Issue by manderss99** [cardigann/cardigann#121]
### Indexer Name
HD Space

### Is the indexer private or public? If private, can you provide an invite?
private, I have 1 invite

### Indexer URL
https://hd-space.org/index.php?page=login

### Indexer language
english

**Comment by kaso17** [comment]
if you can send an invite to kaso1717 -at- gmail.com I can add it.

**Comment by manderss99** [comment]
Invite sent, thanks!
