### ISSUE TITLE
Bug report: Freshon not available in dropdown

### ISSUE THREAD

**Issue by theCheek** [cardigann/cardigann#123]
### Issue experienced
Freshon dissapeared from dropdown
### Steps to reproduce
Click dropdown to add new indexer :)
### Cardigann version (in the footer, or via `cardigann --version`)
1.8.6

**Comment by lxt2** [comment]
It would only not be available if it's already enabled.

**Comment by theCheek** [comment]
Ok, that's the last time I issue a bug report late at night.

Apologies for being such a dumbass!!!
