### ISSUE TITLE
Indexer Request: Scenetime

### ISSUE THREAD

**Issue by wasgehthierab** [cardigann/cardigann#125]
### Indexer Name
Scenetime

### Is the indexer private or public? If private, can you provide an invite?
Private, yes

### Indexer URL
https://www.scenetime.com/

### Indexer language
english

**Comment by kaso17** [comment]
I'll take care of it. Already got an account.

**Comment by wasgehthierab** [comment]
great thank you!

**Comment by wasgehthierab** [comment]
I have an error with this indexer:

"Result row 1 has zero size" 
Version 1.9.3

**Comment by wasgehthierab** [comment]
the message appears but it seems to work
