### ISSUE TITLE
Feature Request: add Manual Search and View Cached Releases

### ISSUE THREAD

**Issue by gurabli** [cardigann/cardigann#13]
It is not a top priority feature, but Manual Search and View Cached Releases would be a nice feature to have, as it is in Jackett.

**Comment by lxt2** [comment]
I've been thinking about this one, what do you use "View Cached Releases" for?

**Comment by aroundmyroom** [comment]
View = did I miss something or why did Sonarr not pick that file I expected to get

Also building the cache will also create the availability to get 'older' content and build an own 'search' function

**Comment by lxt2** [comment]
Latest release has search.

**Comment by lxt2** [comment]
We have search now. I'm going to close this as I'm still not convinced on cached releases (we don't cache releases at present). Let me know if you feel strongly about this @gurabli.
