### ISSUE TITLE
Compile errors for ARM (Synology)

### ISSUE THREAD

**Issue by schumi2004** [cardigann/cardigann#131]
I installed Go and grabbed all the needed packages but i'm getting some errors when i try to compile it for my Synology DS715 system which is ARM based.:

Any suggestions?

12:53:16 (master) ~/github/cardigann$ sudo GOOS=linux GOARCH=arm go build
# _/home/openelec/github/cardigann

./main.go:124: cannot use "github.com/Sirupsen/logrus".DebugLevel (type "github.com/Sirupsen/logrus".Level) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Level in argument to logger.SetLevel
./main.go:260: cannot use "github.com/Sirupsen/logrus".Fields literal (type "github.com/Sirupsen/logrus".Fields) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Fields in argument to log.WithFields
./main.go:336: cannot use "github.com/Sirupsen/logrus".WarnLevel (type "github.com/Sirupsen/logrus".Level) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Level in argument to logger.SetLevel
./main.go:441: cannot use serviceLogHook literal (type _serviceLogHook) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Hook in argument to logger.AddHook:
    *serviceLogHook does not implement "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Hook (wrong type for Fire method)
        have Fire(_"github.com/Sirupsen/logrus".Entry) error
        want Fire(_"github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Entry) error
./main.go:442: cannot use serviceLogFormatter literal (type *serviceLogFormatter) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Formatter in argument to logger.SetFormatter:
    *serviceLogFormatter does not implement "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Formatter (wrong type for Format method)
        have Format(_"github.com/Sirupsen/logrus".Entry) ([]byte, error)
        want Format(*"github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Entry) ([]byte, error)
12:54:05 (master) ~/github/cardigann$

**Comment by schumi2004** [comment]
Mmm I missed the binary already being available for ARM systems.

https://dl.equinox.io/cardigann/cardigann/stable

**Comment by schumi2004** [comment]
Okay, i ran the ARM version on my Synology and it returned this error:

root@DS715:/volume1/@appstore/scripts/cardigann# ./cardigann-edge
runtime: kernel page size (32768) is larger than runtime page size (4096)

Is it possible that archive is corrupt?

11:25:57 ~/github$ wget https://bin.equinox.io/c/3u8U4iwUn6o/cardigann-stable-linux-arm.tgz
--2016-10-19 23:26:24--  https://bin.equinox.io/c/3u8U4iwUn6o/cardigann-stable-linux-arm.tgz
Resolving bin.equinox.io (bin.equinox.io)... 23.21.165.77, 107.20.164.208, 107.20.195.3
Connecting to bin.equinox.io (bin.equinox.io)|23.21.165.77|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4604695 (4,4M) [application/octet-stream]
Saving to: ‘cardigann-stable-linux-arm.tgz’

cardigann-stable-linux-arm.tgz       100%[======================================================================>]   4,39M   637KB/s    in 6,8s    

2016-10-19 23:26:37 (658 KB/s) - ‘cardigann-stable-linux-arm.tgz’ saved [4604695/4604695]

11:26:37 ~/github$ tar zxvf cardigann-stable-linux-arm.tgz 
cardigann
tar: cardigann: Cannot open: File exists
tar: Exiting with failure status due to previous errors
11:26:53 ~/github$

**Comment by lxt2** [comment]
Looks like this issue https://github.com/golang/go/issues/12480

**Comment by lxt2** [comment]
What version of Golang do you have? `go version`

**Comment by schumi2004** [comment]
Version i'm running is:
08:14:14 ~/github$ go version
go version go1.6.2 linux/amd64

Then i'm building it for ARM like this:
GOOS=linux GOARCH=arm go build

**Comment by schumi2004** [comment]
I think i can use the ARM archive from download page but for some reason it's corrupt.
[img]http://i.imgur.com/VNawSJ3.png[/img]

**Comment by maxcore** [comment]
@schumi2004 i use docker for this one in my syno

**Comment by schumi2004** [comment]
Unfortunately my DS715 isn't capable running docker.

**Comment by hbooo** [comment]
I have a DS414 wich is not capable of running docker so I am also interested in an ARM v7 version

**Comment by vinchi007** [comment]
I ran into similar issue with FreeBSD, can someone help to resolve this issue:

```
# make
go test -v
# _/usr/local/etc/cardigann/cardigann
./main.go:124: cannot use "github.com/Sirupsen/logrus".DebugLevel (type "github.com/Sirupsen/logrus".Level) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Level in argument to logger.SetLevel
./main.go:260: cannot use "github.com/Sirupsen/logrus".Fields literal (type "github.com/Sirupsen/logrus".Fields) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Fields in argument to log.WithFields
./main.go:336: cannot use "github.com/Sirupsen/logrus".WarnLevel (type "github.com/Sirupsen/logrus".Level) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Level in argument to logger.SetLevel
./main.go:441: cannot use serviceLogHook literal (type *serviceLogHook) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Hook in argument to logger.AddHook:
        *serviceLogHook does not implement "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Hook (wrong type for Fire method)
                have Fire(*"github.com/Sirupsen/logrus".Entry) error
                want Fire(*"github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Entry) error
./main.go:442: cannot use serviceLogFormatter literal (type *serviceLogFormatter) as type "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Formatter in argument to logger.SetFormatter:
        *serviceLogFormatter does not implement "github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Formatter (wrong type for Format method)
                have Format(*"github.com/Sirupsen/logrus".Entry) ([]byte, error)
                want Format(*"github.com/cardigann/cardigann/vendor/github.com/Sirupsen/logrus".Entry) ([]byte, error)
*** [test] Error code 2

Stop in /usr/local/etc/cardigann/cardigann.


````

**Comment by schumi2004** [comment]
Did a clean install with golang 1.7.4, compiling seemed to work but still have the page size issue @lxt2 linked to. (Synology DS715)
Is there a way to change this page size when compiling?

**Comment by schumi2004** [comment]
Finally got my issue resolved and have a working package for my Synology DS715.
I think the trick was setting environment variable GOARM=7 (for my Synology)

This are my current env settings:
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/openelec/cardigann/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="7"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build984631936=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="0"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

Things i did are:
Install golang 1.8.0 rc3 using this guide http://tecadmin.net/install-go-on-ubuntu/
Changed 1.7.4 to 1.8.0 rc3 version, the rest is the same.

Tried compiling for arm and arm64 without luck until i found this page after reading several comments and commits regarding page size. https://github.com/golang/go/wiki/GoArm
I checked my cpu info using:  cat /proc/cpuinfo
There it listed: model name      : ARMv7 Processor rev 4 (v7l)

Set variables and compile again (still received a few errors but just continue compile steps)

And package runs:
root@DS715:/volume1/@appstore/scripts/cardigann# ./cardigann --version
v1.9.9-6-gf7f27d8

For others interested in this package also you can download it here: https://www.dropbox.com/sh/mubaxpp4qh539po/AADfR9yjkLVEoh2khHgCxpCea?dl=0
