### ISSUE TITLE
Indexer Request: TorrentHeaven

### ISSUE THREAD

**Issue by wasgehthierab** [cardigann/cardigann#134]
### Indexer Name

TorrentHeaven
### Is the indexer private or public? If private, can you provide an invite?

private, no, closed
### Indexer URL

https://torrentheaven.myfqdn.info
### Indexer language

German

**Comment by lxt2** [comment]
I get a certificate error from the front page.

**Comment by kaso17** [comment]
I already added it to Jackett so I could add it to cardigann too.
@lxt2 yes, the siteops conciser a self signed certificate more secure. This is not going to change. Several people already tried to convince them in their forums with good arguments but it's unlikely that this is going to change.
For this one we would need a core change to accept invalid certificates or (my preference) a definition option to accept a specific certificate.

**Comment by kaso17** [comment]
definition is finished.
I'll publish it once we agreed on a workaround for the HTTPS issue.
besides that this tracker has the same problem as torrent syndikat: fuzzytime can't handle the dd.MM.yyyy HH:mm time format (at least not in the USContext)

**Comment by wasgehthierab** [comment]
any news on https?!
