### ISSUE TITLE
Cached info kept after restart?

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#14]
Just found an alternative of jackett (yeah!) .. Jackett is serving my needs, but is crashing all the time and causing me to loose all cached info and just at that time I do miss a number of shows. So looking for an alternative

So .. will cardigann keep the cached info after a restart?

I will try to install the app under debian this afternoon / evening .. 

installation is easy, but now I have downloaded the definitions, unzipped them, but no indexer found when I visit the server page localhost:5060 .. 

issue is related to the service
./cardigann-linux-amd64 service start
when started this way no definitions can be found
when started ./cardigann-linux-amd64 than defs are found but it's not running in the background

**Comment by lxt2** [comment]
Thanks for the report and for testing @aroundmyroom, at the minute Cardigann doesn't do any caching of search results that it has seen, each query to it translates into a query to an indexer. Is that what you meant? Your configuration will absolutely be kept though.

You make a good point about the service installation, it's going to look for the defs in a couple of places and it might not find them. I'll figure out an answer and get back to you.

**Comment by lxt2** [comment]
@aroundmyroom follow https://github.com/cardigann/cardigann/issues/17 for more details on running as a service.

**Comment by aroundmyroom** [comment]
maybe  config.json can be used to store location of defs as under linux user has to 
unzip etc. I prefer to put it in a location where other apps are stored.
/home/[user]/cardigann/xxx/definitions/
/root/.config is also a good place but segmentated is not ok due to the upgrade(s), you do not want to be busy upgrading in various locations (or the release should taken care of that)

**Comment by lxt2** [comment]
Provided your service is running as `userxyz` it will look in `/home/userxyz/.config/cardigann/definitions`. It should put `config.json` in there too. You can see the matrix of where config will live on https://github.com/shibukawa/configdir. Need to make this clearer.
