### ISSUE TITLE
Bug report: [TorrentLeech test fails]

### ISSUE THREAD

**Issue by elmerfdz** [cardigann/cardigann#145]
### Issue experienced

TorrentLeech test fails and I get the following error:

An error occurred
Form not found matching expr 'form'.
### Steps to reproduce

Try adding TorrentLeech as an indexer and then hit the test button on Cardigann next to the TorrentLeech entry.
### Cardigann version (in the footer, or via `cardigann --version`)

1.9.2

**Comment by manderss99** [comment]
Same with privatehd.
Also have 4 indexers fail with message 'no input found with name username' / 'no input found with name password'. They work from sonarr and when searching in web ui though.
Version 1.9.2.

**Comment by Githubtordl** [comment]
@manderss99 Thanks, wasn't aware that the search actually works although it says test failed when testing from the Cardigann dashboard. 

Test is successful from Sonarr

**Comment by lxt2** [comment]
Thanks all, will investigate. If someone was able to run `./cardigann test --debug definitions/torrentleech.yml` and send me the email at rznqsp8ffyeprn2l at gmail.com that would help.

**Comment by manderss99** [comment]
I get error:
Mac:bin manderss99$ ./cardigann test --debug  definitions/torrentleech.yml
cardigann: error: open definitions/torrentleech.yml: no such file or directory, try --help

**Comment by manderss99** [comment]
found this in server output:

→ Testing indexer torrentleech at https://www.torrentleech.org/
  Testing required config is available SUCCESS ✓ in 680.951µs
  Testing login with valid credentials FAILURE ✗ in 705.26549ms
→ Indexer torrentleech FAILED with Form not found matching expr 'form'.
time="2016-10-26T09:14:35+02:00" level=error msg="Test failed" error="Form not found matching expr 'form'."

**Comment by manderss99** [comment]
copied the definition for torrentleech and tried:

./cardigann test-definition  --debug ../Library/Preferences/cardigann/definitions/torrentleech.yml  > test.log

however the debug output is not written in the file, only on screen. How do I get the debug output into a file which I can email?

**Comment by manderss99** [comment]
think I got it:

[debug.log.txt](https://github.com/cardigann/cardigann/files/553807/debug.log.txt)

**Comment by lxt2** [comment]
Thanks, will investigate. There is a fix for torrentleech going out in the next release, hopefully that will help.

**Comment by manderss99** [comment]
please note there are three different error messages:

Form not found matching expr 'form'.
no input found with name username
no input found with name password

and these happens for a number of indexers, not just torrentleech.
I have tested on macos and ubuntu.

**Comment by theCheek** [comment]
FYI, Torrentleech test is still not working, for me I'm getting the error 'No Matches found for Pattern'. 

However when using it for searches, it seems to be working, so I guess not a huge problem :)

**Comment by hadim** [comment]
Same issue here.

**Comment by kailan** [comment]
Hi everyone, I'll look into this now.

Sorry for the delay – there are currently no developers actively working on the project.

**Comment by lxt2** [comment]
Should be fixed now.
