### ISSUE TITLE
Bug in version v1.9.2-1-g50999d2

### ISSUE THREAD

**Issue by kingfenix** [cardigann/cardigann#146]
the Docker container located [https://hub.docker.com/r/cardigann/cardigann/] doesnt seem to retain settings between versions. When I first setup this docker in my unraid server, I had to configure it twice because settings were lost, and now that I updated to this new version it happened again, API was changed and indexers setup were lost.

**Comment by lxt2** [comment]
I'll investigate, going to close in favour of #148.
