### ISSUE TITLE
Docker Questions

### ISSUE THREAD

**Issue by kingfenix** [cardigann/cardigann#148]
I setup the cardigann docker and created all the same variables/paths etc for it that jackett had, and I have it working, but.....

1) the config folder is empty, how do I get access to the config.JSON or the definitions?
2) should I use a $HOME or $CONFIG variable or something?

overall, what are the options and settings for using in UnRAID/Docker?

**Comment by lxt2** [comment]
The config dir is set here https://github.com/cardigann/cardigann/blob/master/Dockerfile#L5

Are you saying there isn't any configuration being written to /.config/cardigann ?

**Comment by kingfenix** [comment]
no I did finally figure out how to add the path correctly in a unraid docker container so that I can now see the config.json, but there seems to be no way to access the definition files in the same scenario? would like to be able to add a definition file and/or play with making a new one or fixing one (programmer here)

**Comment by lxt2** [comment]
If you start cardigann with `--debug` it will show you the paths it looks at to load definition files. They are also enumerated here https://github.com/cardigann/cardigann#definitions. If you mount in the definitions you want to develop to one of those spots, cardigann should load them.
