### ISSUE TITLE
torrents found, but not downloadable

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#15]
http://media.mysite.net:5060/download/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0xNiAyMToxNjoyNS4xMzY0NjMzMSArMDIwMCBDRVNUIiwiZW5jIjoiQTEyOEdDTSIsIml2Ijoic21WeFlKOXo0VWEydWdxMSIsInRhZyI6InAxRHNueUloUnFyYzJzMDFRNXdjRFEifQ.S6ZQ8vDtPumwfwNeHz_XnQ.nlwIdEVLydWY_ssT.QrBQmK_HNAax1Bas7MV2waA-k3Z0q7a98zlCk4pfe4mkRjZDVqiKL8QnogIZzKOqAjKiKxViQnKrjQHmn9FIheZQAxVSk1JCLGyeTk5Nb33e6eKkfuLYC4v-fxvYK1GozhytBOubTDm9YLmO0TUiXT26gk4RXk1GtNuyzXJMAsxJb5v02-83t-mgyXKLqpjn05aWf86LFljF22oyg_VLnn4bdS7FbB2hJspJHi-ZUwCnVVng05DC_I5aQuAV.ZVjfmuUVM-yvxW-l0r7Ujw/Youre.The.Worst.S03E03.1080p.WEB.H264-DEFLATE.torrent/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0xNiAyMToxNjoyNS4xMzY1NTkyOTggKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6ImpnY3lfWFJiTE94cmJBdmEiLCJ0YWciOiJKS3RIUFJLRnVKR25hYlV1S1BZbVZRIn0.1wRxEApeiAbX1kme-seVIA.9jvg1WWpHCbf20-5.fLjcjDJAKn1KvaIoJASELYadE1AV7VZya3TYYdQzzwCJjWsn8f5_4Jr_ypdQ7By62Cl2LH-3vqxqFSXh52Pe81zOK4Upq2866bplCwGAnUq4yjHlSPk57nf8FkI5KZ9NpTunMNxLLCv2zMjc7GWdBORZMSMBjVVnUqnYyTr5AtUbhRvG9C_sRnwii8G_sftmRF2WMo69l5PjA43LmjVHEfBhJpMtewuwcMhs0qziTJjff7Q6v31ALEU8-HZp.64zFa9td1qQydBTnyssI3g/Youre.the.Worst.S03E03.Bad.News.Dudes.Dead.1080p.AMZN.WEBRip.DD5.1.x264-CasStudio.torrent

this is what sonarr tries .. 
but it gets an 404

**Comment by lxt2** [comment]
Which version of cardigann and which tracker was this?

**Comment by aroundmyroom** [comment]
morethan.tv
version is v1.3.0
retrieved with wget as curl example does not work that way due to 302

wget https://github.com/cardigann/cardigann/releases/download/v1.3.0/cardigann-linux-amd64

**Comment by lxt2** [comment]
Could you run a test and see if it passes? Will need to run it in the dir that the binary is and the definitions are. 

```
./cardigann test definitions/morethantv.yml
```

**Comment by lxt2** [comment]
Ok, I think I've tracked this problem down, will be releasing a 1.4.1 soon.

**Comment by aroundmyroom** [comment]
Great !!

test was

Definition file parsing OK
INFO[0000] Testing search mode "search"
INFO[0001] Successfully logged in                        site=morethantv
INFO[0001] Searching indexer                             query=map[t:search limit:5] site=morethantv
INFO[0002] Query returned 5 results                      site=morethantv time=9.545926ms
INFO[0002] Testing downloading torrent                   url=https://www.morethan.tv/torrents.php?action=download&id=32620&authkey=f531daa85515406a07d4104f0de0c617&torrent_pass=ckt1sijsqhkxpam28hiavgz4nmcoq942
INFO[0003] Downloaded 330249 bytes from linked torrent
INFO[0003] Testing search mode "tv-search"
INFO[0003] Searching indexer                             query=map[t:tv-search limit:5 cat:[5040 5030]] site=morethantv
INFO[0004] Query returned 5 results                      site=morethantv time=4.123684ms
INFO[0004] Testing downloading torrent                   url=https://www.morethan.tv/torrents.php?action=download&id=32620&authkey=f531daa85515406a07d4104f0de0c617&torrent_pass=ckt1sijsqhkxpam28hiavgz4nmcoq942
INFO[0004] Downloaded 330249 bytes from linked torrent
Indexer test returned OK


but yeah .. what was downloaded I dunno ;-)

**Comment by lxt2** [comment]
Closed in 4bf73bfdfe52d4d7907e12a82084fc3048ef43c2
