### ISSUE TITLE
Indexer Request: FunFile

### ISSUE THREAD

**Issue by darkcloud784** [cardigann/cardigann#150]
### Indexer Name
Funfile

### Is the indexer private or public? If private, can you provide an invite?
Private, I can provide you with an invite if requested.

### Indexer URL
https://www.funfile.org/

### Indexer language
English

Additional Details:
Here is a python plugin used for couchpotato (I did not write this plugin). I hope this might be able to provide some sort of information to help. https://github.com/arvinsingla/couchpotato.provider.funfile

**Comment by kaso17** [comment]
please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by darkcloud784** [comment]
Invite sent.
