### ISSUE TITLE
Indexer Request: ethor.net

### ISSUE THREAD

**Issue by thenamelessthing** [cardigann/cardigann#157]
Ethor.net

It's private tracker and I can provide an invite!

https://ethor.net/dp#/browse.php

FR/EN

**Comment by JigSawFr** [comment]
@thenamelessthing you cand send me an email to jiigsaaw@protonmail.ch with invite, i will work on adding it asap

**Comment by kaso17** [comment]
I've already started to work on it. I'll finish it soon.

**Comment by JigSawFr** [comment]
Tahnks for your information, i've deleted it of my todo list

**Comment by kaso17** [comment]
Fixed with #235 
Solving #236 would help to make it better.
