### ISSUE TITLE
Unable to install in Windows 10 64 bit

### ISSUE THREAD

**Issue by torrentman** [cardigann/cardigann#162]
When double clicking on the latest, stable cardigann exe as administrator I see a cmd window open very briefly, then quit. No service gets created, and trying to start the service from cmd line shows cardigann not present or not in the path. I don't see a folder created for the cardigann config file in my Appdata. Cardigann server not accessible with web interface, because it is not running.

I uninstalled my anti-virus and disabled the windows firewall and got the same result .. nothing seems to get installed. It appears that cardigann starts and is quickly shut down before it can install. Am I missing a step?  Thanks!
 
Update! I got it sorted out and it's now working fine! Loving it! Thank you for your work!

**Comment by fravia1** [comment]
How did you get this sorted?

**Comment by torrentman** [comment]
Yes! I figured it out an hour after I posted. I updated my post with the last line saying I figured it out. Thanks for asking.

**Comment by sixtyfeight** [comment]
I am also having this exact issue, What did you do to get this to install?

**Comment by torrentman** [comment]
cardigann.exe needs to be manually installed as a Windows service. Put it where you want it (such as in the folder: "C:\Program Files\Cardigann"). Set that path in your Windows Path variable. Then open a CMD prompt, navigate to the folder where it is, and type the following:
cardigann service install
cardigann service start
You can Google for "how to install a windows service" if you need more help.
