### ISSUE TITLE
Failed to match selector

### ISSUE THREAD

**Issue by darkcloud784** [cardigann/cardigann#167]
Recently Funfile was added to the indexer list (which I love) but using it fails with the error message - Failed to match selector "div:has(div#clock) > b:last-child"

**Comment by kaso17** [comment]
I guess this happens if your ratio is != Inf.
@darkcloud784 can you please post the HTML code of your Up/Down/ratio stats line in the header?
Search should work normal anyway

**Comment by darkcloud784** [comment]
@kaso17 Are you referring to the HTML on the element shown on funfile?

<span style="color: #339933;">12.692</span>

**Comment by kaso17** [comment]
Please include the parent div element:
Should look like this:
https://gist.github.com/kaso17/702a98e318d8316d882ae9e3be350a50

**Comment by darkcloud784** [comment]
@kaso17 

This is everything from the header.

`
<div class="head_banner">
<a href="https://www.funfile.org"><img src="https://www.funfile.org/themes/Halloween/images/blank.gif" style="width: 100%; height: 120px; margin-bottom: 0px;" alt="" /></a>

<div style="float: left; margin: 5px 0 0 14px;">
<a href="https://www.funfile.org/userdetails.php?id=415773" style="font-weight: bold;">darkcloud784</a>
<br />
<b style="color: #660000;">Clinical</b>, <a href="https://www.funfile.org/invite.php">2 invites, <a href="https://www.funfile.org/mycredits.php">594.29 cr.</a>
</div>
<div style="float: right; text-align: right; margin: -6px 14px 0px 0px;">
<div id="clock">Server Time: 17:11:11 CET</div>
Currently <font color="green">Connected</font>: <b><a href="/usertorrents.php?id=415773#seeds"><font color="black">24</font></a></b> up, <b><a href="/usertorrents.php?id=415773#leech "><font color="black">1</font></a></b> down | Max 50 DL Slots
<br />
Total: <b>3.887 TB</b> up, <b>3.822 TB</b> down, <b><span style="color: #339933;">12.692</span></b> ratio, <a href="/userhr.php?id=415773"><font color="red">1</font></a> <a href="/userhr.php?id=415773&free=1"><font color="orange">(3)</font></a> H&amp;Rs
</div>
<div style="clear:both;"></div><div style="text-align:center; position:relative; bottom:12px;"><p>You need to <b>upload</b> another <b>46.113 TB</b> to reach the next class.</p></div></div>

`

**Comment by darkcloud784** [comment]
Still nothing?

**Comment by darkcloud784** [comment]
Updated, now getting this...

Failed to match selector "a[href^=\"download.php\"]"
