### ISSUE TITLE
Clarify where Cardigann looks for definitions and config

### ISSUE THREAD

**Issue by lxt2** [cardigann/cardigann#17]
On linux, cardigann will search the following dirs for config and definitions:

 * /etc/xdg/cardigann/cardigann
 * $HOME/.config/cardigann/cardigann (where $HOME is the user that runs the service)
 * $CWD

This should be made clear in the docs, and ideally the top level path should be /etc/cardigann.

**Comment by aroundmyroom** [comment]
ok, that is clear
indeed docs can help here. but as the config.json is also not put there I opt to add the location in the config.json ;-)
