### ISSUE TITLE
Bug report: TorrentPotato implementation returns size in KB instead of MB

### ISSUE THREAD

**Issue by qja** [cardigann/cardigann#182]
### Issue experienced
CouchPotato ignore many results from Cardigann because file size are too big. This is because of a slight bug in TorrentPotato implementation in cardigann which return the file size in kb instead of mb in field size. For example:

curl "http://192.168.6.88:5060/torrentpotato/torrentleech?imdbid=tt0387808&search=Idiocracy&passkey=XXXX"
{
  "results": [
    {
      "release_name": "Idiocracy 2006 720p HDTV x264-x0r",
      "torrent_id": "https://www.torrentleech.org/torrent/538891",
      "details_url": "https://www.torrentleech.org/torrent/538891#comments",
      "download_url": "http://192.168.6.88:5060/download/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsIjoiaHR0cHM6Ly93d3cudG9ycmVudGxlZWNoLm9yZy9kb3dubG9hZC81Mzg4OTEvSWRpb2NyYWN5LjIwMDYuNzIwcC5IRFRWLngyNjQteDByLnRvcnJlbnQiLCJuYmYiOjE0NzgwMzA1MjYsInMiOiJ0b3JyZW50bGVlY2gifQ.xgLyf3iUS2jDHuf5yGmOiAz2EAPm9JumIlnn6MHURn4/Idiocracy+2006+720p+HDTV+x264-x0r.torrent",
      "imdb_id": "",
      "freeleech": false,
      "type": "movie",
      "size": 1337890,
      "leechers": 0,
      "seeders": 139
    }
  ],
  "total_results": 1
}
From https://github.com/CouchPotato/CouchPotatoServer/wiki/Couchpotato-torrent-provider :
 - size: integer in MB

### Steps to reproduce
Run a query and look at size field.
### Cardigann version (in the footer, or via `cardigann --version`)
1.9.3

**Comment by justinatwell** [comment]
+1 for this.  Temporary workaround I'm using is set all CouchPotato qualities minimum "0" and maximum "9999999".  Still can't tell what size it really is in CouchPotato because the size column is too small to display 133.789 GB (haha).

**Comment by fromthewoods** [comment]
This seems like it should be easy enough to fix.

**Comment by lxt2** [comment]
Interesting, is this just for torrentleech?

**Comment by lxt2** [comment]
Apologies, I just read that this affected TorrentPotato specifically.

**Comment by lxt2** [comment]
I haven't had time to test this, but I believe that should fix it.

**Comment by justinatwell** [comment]
Updated to edge (Cardigann 1.9.3-20-g871e7c1), and still having parsing issues.

Example from CouchPotato logs:
`11-12 08:48:19  INFO [core.media.movie.searcher] Wrong: "The Imitation Game 2014 720p BluRay x264-x0r" is too large to be 720p. 1962890MB instead of the maximum of 80000MB. `

Manual search in Cardigann shows size as 1.87 GB.  Website shows size as 2.014 GB (close enough?).
