### ISSUE TITLE
as simple as possible HowTo for how to add support for a new Indexer

### ISSUE THREAD

**Issue by psyoptix** [cardigann/cardigann#198]
Seeing as one of the most common feature requests is to add Indexers and my understanding is that Cardigann was designed specifically to make it half-way tractable for a non-programmer to add support for Indexers I think it would help the Cardigann community a lot of an as-idiot-proof-as-possible HowTo were developed for adding Indexers (especially if there were an easy way to share the results).

**Comment by lxt2** [comment]
Yup, #5 definitely needs doing! Apologies, I've been short on time. I'd welcome any help and would certainly contribute if someone wanted to make a start.
