### ISSUE TITLE
Feature request: Access Via External IP for Service

### ISSUE THREAD

**Issue by BetaLeaf** [cardigann/cardigann#199]
### Access via external ip for service
Because I run a server for everything, I want to be able to access Cardigann via an external ip or ddns.

### Justification
I can access the server but it never loads. It just a white screen.

### Example use case
Change bind address from localhost:5060 to x.x.x.x:5060 where x.x.x.x is your external ip address.

**Comment by lxt2** [comment]
The server command has a `--bind` parameter.
