### ISSUE TITLE
Download can still fail

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#21]
Lucifer.S02E01.1080p.HDTV.X264-DIMENSION	MorethanTV Carnigann	2.0 GB --> will fail
Lucifer.S02E01.720p.HDTV.X264-DIMENSION	MorethanTV Carnigann	861.8 MB --> ok

Problem is that the test does not show a fail
the debug gives me a lot of 'garbage' so I cannot find out why it is failing (yes, 1080p is not in my wanted list, but I want to pick it manually if I desire)

DEBU[0018] GET /download/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwODowMDoxNS4wNzM5ODE0NzkgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IkxvQkk4bHNwc01mdmxWWkoiLCJ0YWciOiJUeTJWRDhkMm9iMkExX1RVeU9QWUp3In0.kkjCOHN4PzizCPh-4CuepA.ZmFm13-3L-IEBbZZ.WOrFpk1_4OXxs2zfUy5dLq0OKM8IJwTB8uBSqZ1tOczcrsiawncEvs3vXKN2UnN9YKO6x1ZOh0kWZwVMtK7B2O943tYU-5B3gYXet1WPIu-qxoxTlhztikgwzObLFqFofrXOfzcfj7v2AGiOwZjq17QJuv01eBjhoofilcI5iinmOHqn22W81IxrnEwLYWqXNx-UznCQkbV-b47O_BiRzllPEN49w9V3Kc9mnNejoOv5VIoUAz5oPY2i0hO1.aUf-N0_63vzBoPi0Gs_f4A/Lucifer.S02E01.720p.HDTV.X264-DIMENSION.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwODowMDoxNS4wNzQwOTU4NDIgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IkcwNmpCZmpBdTVjSFFzcTgiLCJ0YWciOiJmcWFoZm1rU0plZkRoejJuMWRQOVJnIn0.UkcYFB-5a7RYjisfPy3XLQ.DMdroDajK5h3s7of.1MgsZD9KTnvjw9zTXL1Dv4K4l6fDMzENAMBH71FyakjQMlett8JYKM4sva61cgzicqtqWU_4ZOvUpTPTE1BUzMBrraQC_dLS0x7VMu61LhwA1nWSQQf8EJHlNB6XEB54uKxd0BNXtI_FfJLZPldX_8dHjche0tRkom0iOEjOPKS7FbuBHG0UDyeMfupiAuDfk87bGS1qM-e9Z7Z_HImGLDxDfQNUcINd7ebfAuSPi5AKQAaKn1Mo8VBR5A2-.aT1-Zn1ZgnHTWoN9EMjunQ/Lucifer.S02E01.1080p.HDTV.X264-DIMENSION.torrent  

method=GET path=/download/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwODowMDoxNS4wNzM5ODE0NzkgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IkxvQkk4bHNwc01mdmxWWkoiLCJ0YWciOiJUeTJWRDhkMm9iMkExX1RVeU9QWUp3In0.kkjCOHN4PzizCPh-4CuepA.ZmFm13-3L-IEBbZZ.WOrFpk1_4OXxs2zfUy5dLq0OKM8IJwTB8uBSqZ1tOczcrsiawncEvs3vXKN2UnN9YKO6x1ZOh0kWZwVMtK7B2O943tYU-5B3gYXet1WPIu-qxoxTlhztikgwzObLFqFofrXOfzcfj7v2AGiOwZjq17QJuv01eBjhoofilcI5iinmOHqn22W81IxrnEwLYWqXNx-UznCQkbV-b47O_BiRzllPEN49w9V3Kc9mnNejoOv5VIoUAz5oPY2i0hO1.aUf-N0_63vzBoPi0Gs_f4A/Lucifer.S02E01.720p.HDTV.X264-DIMENSION.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwODowMDoxNS4wNzQwOTU4NDIgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IkcwNmpCZmpBdTVjSFFzcTgiLCJ0YWciOiJmcWFoZm1rU0plZkRoejJuMWRQOVJnIn0.UkcYFB-5a7RYjisfPy3XLQ.DMdroDajK5h3s7of.1MgsZD9KTnvjw9zTXL1Dv4K4l6fDMzENAMBH71FyakjQMlett8JYKM4sva61cgzicqtqWU_4ZOvUpTPTE1BUzMBrraQC_dLS0x7VMu61LhwA1nWSQQf8EJHlNB6XEB54uKxd0BNXtI_FfJLZPldX_8dHjche0tRkom0iOEjOPKS7FbuBHG0UDyeMfupiAuDfk87bGS1qM-e9Z7Z_HImGLDxDfQNUcINd7ebfAuSPi5AKQAaKn1Mo8VBR5A2-.aT1-Zn1ZgnHTWoN9EMjunQ/Lucifer.S02E01.1080p.HDTV.X264-DIMENSION.torrent remote=127.0.0.1:59864

or is it caused by the terrible long URL being created?

**Comment by aroundmyroom** [comment]
See here log of Sonarr.. 

16-9-20 04:48:55.9|Error|Deluge|Downloading torrent file for episode 'Gotham.S03E01.720p.HDTV.X264-DIMENSION' failed (http://media.xxxx.net:5060/download/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MT
c2NTc2MTcgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6InJ3ekpvbUxnZ3AxRmNISkYiLCJ0YWciOiJxLUpfeGR4dlVHUXp2WFhTWWJfWGlnIn0.cFfWEPIrpUaWb8NCyjQ9hQ.6gomuhN0Yjo2QBY-.bXwh49QhWCA0tTx7i6dWrpe7KR2C8NRJvy__dO7hTxQTEhGXP2adfeac-cHC2smSSiO8jco_6vD
TsQZ3mdhMC1R2dFIsuY5I6KqvvPvDx3OBbO1KKsG7XdG5-V3HDlTguWqtdpkspDbWUTC6CjdlbhFSnUU4C9C8TNXNDotCO2pcYHy1pA81XslIzrj9uyv1G9hoC_SvNH8Vc1SzYFabakfGnaogSZAw6ikpOmIqxtNk33EMVE8mAvdidow.cFCpI40KLoCoMjTX51I7hQ/The.Flash.2014.S01.720p.BluRay.DTS.x2
64-DRACULAadventure.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MTc3ODA1MzUgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IjYxdUgzdThjbUJRR2VDaEQiLCJ0YWciOiJPbm01a1ZRNHl3Q3dodUhWUVlYZzF3In0.94BuSCdz57CAD-
1jkRG93w.x8jcxFae5RvHYytz.zbckZ-6xy2XwG3DkHhOTiqEW8zCev_n0lZLPPsUnSXBs-NaZNH4iq_6WesE1uK55o5a0PqARTAV_L-fPdS9H9tJNEud-cyjfMyvaRKehafAN-NGteORv4mtqkT0rpf2Yqj0Fihbk8IxlYqyN1Yj9c6OyZSKZljSkQeYEW51gXueazgpImH1fSlknXvuh1iAMoLMe_CA1QA7WkkvBpRV
GhorhnCQDdQgfBzCpx_c6NmzDy652_O2-1C-LJBGV.kH5mI65We62rwjKqGRpopg/The.Making.of.the.Mob.S02.720p.WEB-DL.AAC2.0.H.264-DRACULA.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MTc4ODMyICswMjAwIENFU1QiLCJlbmMiOi
JBMTI4R0NNIiwiaXYiOiJmbm5fVk8wVDNPT2FaYzJtIiwidGFnIjoiVkhETU16TGgxaUlYaUl4QzdfOC1TQSJ9.gEeIN24NN6f9WWDtgwQg8g.vQJSFGtj-MS9VPRP.XV4PHlGILcwEkrU85IMFZ3_tSTsIj2qCgnzh1nLqNmZHPNyv-zog7M69w-mw65xvxJ_TI3h9z2eyIL-UIpjga0glpxuSSX1uvsTgNReAbl1Y5r
LrQG9-iMXF_xNGcRGKTd53bk0_ui-ZPfFp5yhNy3bTUNQfn167z0juYtmHDF3PtItd4hDtYfooa3KYOLUr2SAbkItpcQCIO7czZHHYBvzz2iCNbAVbJMGoS3Vg86PqNhKaVD3r3k-QpM4-.jHrGbRE0tcsfaQgaQthxSg/The.Strain.S02.720p.BluRay.DD5.1.x264-DRACULAthriller.torrent/morethant
v/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MTc5ODU5NzIgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6Ii1UR2FQZTZKY3hFWGFBbXQiLCJ0YWciOiI1U1phWjEwOHJEUUljeDR2Y0ZjeGtnIn0.egKQRCR_eAVqH6hjRXx07A.VODKwzJRc97j-k57.4UwLheNYofX
GMz2JNXd9M5WJnMLKb3kH_PUoXSxBB-WL3ExrU8J5Qzo92qetbA9hLSZsIwgQX4xdHBrGezzfwDQWvTAogOjZoEkmVRDGuBW3EZbfn4ixM8ktZL_G4OZNpAcl5-W5y2WBMEsFCsNiYTC7l-CcXxXcVc8YID1GpnwgjpPdEEAqWUxybMSjXBAPvFSn_xtpXXIqM898wSdbwaWCYBz-gKCZXU7_7VSb620X2aSckwzbN_Qn
Iq9B.5buD9BxGJCpQK9uquYVKlg/Narcos.S01.720p.BluRay.DTS.x264-DRACULAcrime.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MTgxMzI1OTcgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IjEzdFZnSEVPY2lVTTFLZkUiLCJ0Y
WciOiJfVnhScEU2UTBpZjdxTWxkVXc4ZVFnIn0.pxzzd8bwU7IHwtyslBDDuQ.gdDoJxHL5sNcF-NF.ufkx_GLVfAjceOMH8AoxpH86e8-lJBpKnunfoXDqvLJPwpCZx3mv8eHwWLOHrttWj8BBhHfjjrez0Q5CzsUhDrui9Kio51GpN8NsKJewWXKLsZ-kMwQjschDLFkao0rH5GAOlmcGGOtH-jXtb1xKP_YiHiq60-
Usti-n-0ZMfaRQu0F624_pBrCDWPLB2CoKeG6aH87qBGBNS_HuU9KsaucEia_vpsa7sGpA60A-dueTgJ8lsXoWxDIOq2lH.T3v9TnrX-_7StmaEO7F0lw/Fear.the.Walking.Dead.S02E12.720p.HDTV.x264-AVS.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0
ODo0MC45MTgyNDc0MTIgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6ImV1UnYzUDNhQjJ1MHdWdlYiLCJ0YWciOiJDbEkyWUN6Zl92Y2tfNFNDSEFta0xnIn0.vkxScjXtJi8DWxMjejGAhg.LnGkoaexPFhrjNNa.kpo-4v8-7JFKNtsm-14xYfeWfqiVdefAaZojVKCeRSy8gKxhM9VYZqw6bICiylKtI
48LC6NozOvoNFUBwnZgDunVkcDqxF1Y4dPWU5GJww0irpZR5b3TJetZWT_mupuguE-yWwcFY6gZIVi9l0KJgZ3qE97lR9xT4lHT7GQS6QS5iW4Gw8c0OcX9NRjTpJGPFh3KzTQBsoVJZKtpq_A9TcI0DaCj7Jp5Zl-RGId47P6UIbfh7YUE9PHxVSr2.sks--mbXMSPLit6Ywu3BcQ/Ray.Donovan.S04E12.720p.HD
TV.x264-AVS.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MTg0MDMwNzYgKzAyMDAgQ0VTVCIsImVuYyI6IkExMjhHQ00iLCJpdiI6IlM0ckVETmw2NndLUVZYaXMiLCJ0YWciOiJsWDdfTXRHeVY1VFowZVZzZGFvSExnIn0.jnzlV9kT0FNDhNPI3WRufg
.XU2qkjtcuczOgyJ1.6ue5tveFuxr4DetbdxGY07rK36oUvGYMcQtjRX8nIWAIlXwW2AVYbsXeluNKd72O4xQ2at1T1zdYP6aNMgx3G9-iOtHBzb_VtIIWOdk3kv6xnJfM7XUpzIEjaLoTgK4JXOblz3mqN6A3A8Z2_opm4KW_7HDjz3QmlK7c6VXtq5TixudDMmPZyDYhPTS6UkP8pWEr5-UAsGxcA3s0n1-6BeHqRek
sqlzH5YT7vIpWUAavuKMvQtXXojTSmOHl.cXZ5Y5cI9c2AYP9i3DpNzQ/The.Strain.S03E04.720p.HDTV.x264-AVS.torrent/morethantv/eyJhbGciOiJBMTI4R0NNS1ciLCJjIjoiMjAxNi0wOS0yMCAwNDo0ODo0MC45MTg1NTc3ICswMjAwIENFU1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiJ2Q041VnND


multiple torrent sources as one ..  causing also an issue with Sonarr telling that the indexer is not available.

**Comment by lxt2** [comment]
Will investigate. Thanks for the report. Those very long urls are encrypted tokens, I will perhaps consider using something shorter.

**Comment by aroundmyroom** [comment]
if I need to do some debugging .. let me know .. right now I cannot use cardigann :-(

**Comment by lxt2** [comment]
I can reproduce the error, working on it.

**Comment by lxt2** [comment]
Figured out the issue, will put out a new release shortly.

**Comment by aroundmyroom** [comment]
that was not a little change ;-)
