### ISSUE TITLE
Torrent files downloaded through Cardigann get "www" added to their tracker announce URL

### ISSUE THREAD

**Issue by lolmancgn** [cardigann/cardigann#219]
It seems that torrents downloaded through the Cardigann-provided Torznab or Torrentpotato APIs, as well as the Cardigann web interface, get `www` added to the torrent's announce URL. So instead of this correct announce URL:

`https://a.trackername.xy/xxxxxxxxxxxxxxx/announce`

we're getting:

`https://a.www.trackername.xy/xxxxxxxxxxxxxxx/announce`

leading to the following error in Deluge:

`trackername.xy Error: Host not found (authoritative)`

The error above might not be reproduceable on any tracker, but I was able to replicate on two private trackers I've tested this on.

A quick comparison between the two torrents files also shows this peculiar difference. The file download from the tracker website has no www inside the URL at the beginning, the torrent file downloaded through Cardigann has.

A possible solution would be to allow a config flag inside of the definition file that returns a boolean for `tracker_announce_www` or something similar. 

Thx and keep up the great work!!

**Comment by lxt2** [comment]
That's very bizarre, I can't think of anything that would be modifying the torrent. I'll see if I can reproduce it.

**Comment by lolmancgn** [comment]
Thanks lxt2! I've also double-checked the URL that's parsed from the site — it's the same that I use to manually download. Please keep me posted and let me know if there is anything at all I can do to help.

**Comment by lolmancgn** [comment]
Alright, I'll purge myself... I've actually added `www` to the Tracker URL inside Cardigann even though any URL that tracker uses is based on the http://tracker.xy schema, foregoing `www`.
