### ISSUE TITLE
public tracker https://torrentproject.se/

### ISSUE THREAD

**Issue by Dnkhatri** [cardigann/cardigann#22]
This seems to be good public tracker for cardigann with search and rss feeds
https://torrentproject.se/

**Comment by camjc** [comment]
Looks like their API is down for now. We could re-open this Issue if/when they bring it back online https://torrentproject.se/about

**Comment by mmarquezs** [comment]
I have been checking this one, it's not easy, they use cloudfare and when trying directly  with curl or wget I get "503 Service Temporarily Unavailable" mean while in the browser works fine. (Basically it's the screen when cloudfare "checks" your browser.) 

I have a curl I got from firefox with the cookie and headers etc... that works but I tried putting the cookie as a setting in the definition so it requires to login with the cookie but even with that  it doesn't seem to work. 

One of the things I know for sure is that the cookie must be used with the same UserAgent that it was created if not it doesn't accept it. Used the same UserAgent from cardigann to get the cookie and then use it in curl with that user agent and it works but it still doesn't work in cardigann. Probably this needs some changes in the program itself to work.

**Comment by lxt2** [comment]
Interesting, sounds like a challenge :)

**Comment by krikv** [comment]
Would be interested in this one also :)

**Comment by ldexterldesign** [comment]
See https://github.com/cardigann/cardigann/issues/324#issuecomment-331602043
