### ISSUE TITLE
Indexer Request: AlphaReign

### ISSUE THREAD

**Issue by putty182** [cardigann/cardigann#233]
### Indexer Name
AlphaReign

### Is the indexer private or public? If private, can you provide an invite?
Private (1 invite available).  DHT-only magnet indexer.

### Indexer URL
hxxps://alphareign.se/

### Indexer language
English (en-us)

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll have a look at it.
If the csrf token is only on the login using simple inputs it shouldn't be a problem.
If CSRF tokens are needed for the search too it will be a problem.

**Comment by putty182** [comment]
Invite sent;  I've got PR #238 mostly working sans date parsing, although this should be easy for someone who knows what they're doing.  There's unix timestamps available as data-attributes, or YYYY/MM/DD text.

There's CSRF tokens on all forms, but it doesn't seem to be implemented on search (ie: fudged / missing values seem to work fine).

**Comment by kaso17** [comment]
With #243 it should be usable.
I've also added the definition file to Jackett, currently it works a little bit better there as it's not affected by the Cardigann limitations mentioned in the PR.
