### ISSUE TITLE
t411.yml not working?

### ISSUE THREAD

**Issue by MIKAd3v** [cardigann/cardigann#249]
Hello,

I've tested the t411.yml directly from the Cardigann web UI:
- I'm obtaining no results in SEARCH mode.
- When I directly click on the TEST button, the following message appears _"An error occurred - Failed to match selector "td:nth-child(7)---" "_.

**Comment by JigSawFr** [comment]
Hello,
What query are you using ?
For movies or TV ?
I'm using it without problems :)

**Comment by MIKAd3v** [comment]
Hello,
After pulling the latest Docker image, testing it again (and getting the same error), restarting the Docker container, testing again... guess what? It's now working!
So what is the point here? Using Cardigann in a Docker container seems very touchy on the network side (slow network bandwidth, packet losses).

**Comment by JigSawFr** [comment]
@MIKAd3v Great if it's solved for you.

Known problem with T411 is TV searching return so many irrevelant results ...
Search of T411 is a pain ! We need to fill some more fields to have better results
