### ISSUE TITLE
Search on all indexers

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#26]
Search on all indexers should only on enabled trackers and or with a switch the public trackers

I only have one or 2 trackers and do not want to bang the other private trackers with incorrect (not available) username / passwords

All Indexers	/torznab/aggregate
ie from debug:
</font> site=hdtorrents
ERRO[0499] Failed to login                               error=Erroneous password or validation code site=demonoid
ERRO[0499] Login failed                                  error=Erroneous password or validation code site=demonoid
WARN[0499] Indexer "demonoid" failed: Erroneous password or validation code

this feature is only usable when trigger only on enabled trackers

**Comment by lxt2** [comment]
Yup, good point. That was my intention, if it's not doing that it's a bug. How are you finding everything else in the latest release?

**Comment by aroundmyroom** [comment]
Right now I am still not able to use it (cannot compile the application under my debian environment)
But 
- I like the version (even the vv in the console is gone ;-)  in the UI
- I like the search option (but would rather see it extended with more info about the torrent (date) or possible use the episode / season info (Ballers S02E01) .. it's not necessary to give 'all' releases
- Test option works great
- I use it now in a 'screen' session so that I can check what is in the console
- if it downloads, than Jacketts can be gone ;-)
- I also like the number seeders

So in the end if it works .. Awesome app ;-)
