### ISSUE TITLE
abnormal and t411 not in the list

### ISSUE THREAD

**Issue by raspdealer** [cardigann/cardigann#262]
Hi,

After the update to 1.9.4 , they are missing...
What should I do? :(

Thanks!!!

**Comment by zeflash** [comment]
You need to create a "definitions" folder in the right place (along with the config.json) and add the YML files you're interested in from the repository folder into that definitions folder.

**Comment by raspdealer** [comment]
Doesnt work for me.. and we should not have to...

**Comment by kaso17** [comment]
@raspdealer: you shouldn't have too, yet. But it seems like there's something broken with the auto-build setup. It doesn't rebuild the internal definitions and @lxt2 hasn't been around for a few weeks now to fix it. That's why you have to place them in a definitions directory  (see README) manually.

**Comment by raspdealer** [comment]
@kaso17 Thanks. I already made the definitions folder and grabbed them by wget.
They are still missing.
Is there any extra steps?

**Comment by kaso17** [comment]
Try using the test-definitions mode with the full path to see if there's any problem with your downloaded files. Otherwise you most likely put them into the wrong directory.

**Comment by raspdealer** [comment]
is that ok?
/home/pi/.config/cardigann/definitions/abnormal.yml

**Comment by raspdealer** [comment]
I was run this 
```
pi@raspberrypi:~/.config/cardigann/definitions $ sudo cardigann test-definition abnormal.yml
→ Testing 1 definition(s) (1.9.4/linux/arm)
→ Testing indexer abnormal at https://abnormal.ws
  Testing required config is available FAILURE ✗ in 1.804979ms
→ Indexer abnormal FAILED with No value for abnormal.username in config
```

For me this is the proof that the system if finding my added definition... but failing (of course) because no configuration.
But why the definition is not in the homepage list which let me generate a configuration page?

**Comment by raspdealer** [comment]
I have tried exactly the same with Xthor.

- Not listed in available indexer list
- I've added credentials manually in the config.json
- the test finish OK
- Not displayed in configured indexers list

I guess the issue is bigger than excepted, manually indexers seems to not be well managed

**Comment by kaso17** [comment]
Try "/etc/xdg/cardigan/definitions" as path, make sure the permissions are ok. If that doesn't work I'm out of ideas.

**Comment by raspdealer** [comment]
OK this is working as a workaround.
Indexers are now listed ad available but I add to reconfigure them manually despite of the config.json already filled.

**Comment by raspdealer** [comment]
Hi @kaso17,
Any news from @lxt2 ? :)

**Comment by kaso17** [comment]
no, I'm starting do doubt that he's ever coming back.

**Comment by JigSawFr** [comment]
I agree, not seen here since nov. 12 2016 10:39

**Comment by raspdealer** [comment]
Someone else can fix this? :S

**Comment by arckosfr** [comment]
Same here

**Comment by raspdealer** [comment]
@lxt2 @kaso17 it seems there is still a build issue.
Even after update to 1.9.9, new definitions aren't in the list until I forced them inside /etc/xdg/cardigann/definitions...
