### ISSUE TITLE
Indexer Request: RARBG

### ISSUE THREAD

**Issue by armani316** [cardigann/cardigann#263]
**Indexer Name**
RARBG

**Is the indexer private or public?** 
Public

**Indexer URL**
http://rarbg.to/index8.php

**Indexer language**
English

**Comment by zductiv** [comment]
#190 Duplicate

**Comment by kaso17** [comment]
added with https://github.com/Jackett/Jackett/commit/d01710c285b86cf704b10ad7a41d8d782c85ee0b
