### ISSUE TITLE
Installing on Raspberry Pi 2

### ISSUE THREAD

**Issue by boec** [cardigann/cardigann#27]
Annoyed at Jackett crashing, so I'd like to try this. I'm not that great at Linux (Raspbian), but what is the process to get this running? All the commands for installation would be helpful. 

EDIT: Got it working, just need to figure out how I can auto start it on boot

**Comment by aroundmyroom** [comment]
what did you do? ;-) would be nice for sharing ;)

for starting at boot": I believe you can install it as a service, but make sure it can find the definitions.

**Comment by boec** [comment]
**I did this:** 
sudo mkdir cardigann
cd cardigann
sudo wget https://github.com/cardigann/cardigann/releases/download/v1.6.0/cardigann-linux-armv5 
sudo chmod +x cardigann-linux-armv5
sudo wget https://github.com/cardigann/cardigann/releases/download/v1.6.0/defs.zip
sudo unzip defs.zip
nohup ./cardigann-linux-armv5 server &

then it's accessible on port 5060.

Going to start from fresh in the morning. Hopefully someone can help me with getting it to boot up automatically.

**Comment by boec** [comment]
Well I tried installing it as a service... but now it won't find the definitions... I've literally put them in every folder mentioned in the issues. ;l

**Comment by aroundmyroom** [comment]
welcome to the group ;-) I am running it in screen due to some testing .. and I believe the startup part will be 'fixed'

**Comment by lxt2** [comment]
The service stuff should install it as a service using whatever is available on your distro, e.g upstart, systemd. Could you able to run `cardigann service --debug  install` and post the output here? 

What user are you running the service as? I'll do some work on clearing up the config loading stuff and make it clearer.

**Comment by lxt2** [comment]
I'm going to close this. Feel free to comment if it's not been resolved for you @boec.
