### ISSUE TITLE
Bug report: Review/fix add http://scenetime.com/ indexer

### ISSUE THREAD

**Issue by ldexterldesign** [cardigann/cardigann#276]
Hey

Thanks for software

### Issue experienced

Unable to add https://www.scenetime.com/ - perhaps a cookie string formatting issue, I don't know - is anyone else experiencing this problem?

### Steps to reproduce

n/a

### Cardigann version (in the footer, or via `cardigann --version`)

1.9.4

```
→ Testing indexer scenetime at https://www.scenetime.com/
  Testing required config is available SUCCESS ✓ in 361.572µs
  Testing login with valid credentials FAILURE ✗ in 492.304392ms
→ Indexer scenetime FAILED with Login check after login failed
ERRO[5199] Test failed                                   error=Login check after login failed
→ Testing indexer scenetime at https://www.scenetime.com/
  Testing required config is available SUCCESS ✓ in 262.947µs
  Testing login with valid credentials SUCCESS ✓ in 303.173159ms
  Testing search mode "search" INFO[5240] Searching indexer                             query=limit=3&t=search site=scenetime
WARN[5241] Row #1 has unparseable size "": strconv.ParseFloat: parsing "": invalid syntax  site=scenetime
WARN[5241] Row #1 has unparseable leechers value "598.533MB" in leechers  site=scenetime
WARN[5241] Row #2 has unparseable size "": strconv.ParseFloat: parsing "": invalid syntax  site=scenetime
WARN[5241] Row #2 has unparseable leechers value "4.393GB" in leechers  site=scenetime
WARN[5241] Row #3 has unparseable leechers value "742.060MB" in leechers  site=scenetime
WARN[5241] Row #3 has unparseable size "": strconv.ParseFloat: parsing "": invalid syntax  site=scenetime
INFO[5241] Query returned 3 results                      site=scenetime time=203.327125ms
FAILURE ✗ in 512.368143ms
→ Indexer scenetime FAILED with Result row 1 has zero size
ERRO[5241] Test failed                                   error=Result row 1 has zero size
```

Let me know if you have any issues - happy to help

Hope this is clear/useful

Yours hopefully

**Comment by bdeluca** [comment]
Is there documentation some where about what you should enter as the cookie value when you set up this indexer? I cant figure it out.

**Comment by mmarquezs** [comment]
@bdeluca Look this: https://github.com/Jackett/Jackett/wiki/Finding-cookies

**Comment by ldexterldesign** [comment]
Hey @mmarquezs,

Thanks for reply

I wasn't aware of that dev' tools section (in Opera [same thing as Chrome]), but nevertheless my cookie string was/is correct

Still failing tests, but able to pickup search results - very strange

I guess I'll wait for https://github.com/cardigann/cardigann/issues/277 to be answered...

Hope to hear back

Yours faithfully

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
Appears to be fixed (for me) now so I'll close this issue

Hope this is useful

Kind regards
