### ISSUE TITLE
Request: remove cache file(s) from /tmp/

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#28]
Please allow from GUI to clear cache out of /tmp/

Downloads do proceed now with v1.6.1

DEBU[0137] Processing download via handler               DEBU[0138] Wrote page output to cache                    file=file:///tmp/morethantv488806656 site=morethantv

especially there is no cleanup if  you start /stop the app

**Comment by lxt2** [comment]
I might add another flag to enable that output caching behaviour. It's really only useful for the test command.

**Comment by lxt2** [comment]
Ok this is done.
