### ISSUE TITLE
Make port configurable

### ISSUE THREAD

**Issue by jscottdouglas** [cardigann/cardigann#280]
Please add a command for the web port to be configurable thanks.

**Comment by kblanks** [comment]
@jscottdouglas From looking at the code, it seems you can set the `PORT` environment variable (this is undocumented).

`PORT=80 cardigann server`

**Comment by lxt2** [comment]
Going to close this, let us know if setting the environment isn't adequate.

**Comment by lehades** [comment]
@lxt2 

I can't seem to get this working on windows ¿any further info/documentaion i should be looking at?

**Comment by kblanks** [comment]
I've always just run `cardigann server --port=<port>`, seems to work fine.

![cardigann server --port=2017](https://i.imgur.com/mkzCJuH.png)

**Comment by lehades** [comment]
AFAIK that works for the manual start, not for the windows service

¿is there any way to change the port as a windows service?

**Comment by jangrewe** [comment]
It would be great if Cardigann:
1) didn't use the official SIP port 5060, and
2a) allowed setting the port in the config.json, or
2b) allowed setting the port as an argument to `service`
3) allowed setting the path to the config, as `$CWD` of the binary doesn't seem to be checked when ran as a service

Thanks!
