### ISSUE TITLE
Can't install as service.

### ISSUE THREAD

**Issue by hwwilliams** [cardigann/cardigann#299]
Cardigann service install returns, "cardigann: error: Failed to install Cardigann Proxy: Access is denied., try --help"

I've tried the command in normal and admin cmd cause I wasn't sure which it was supposed to be, normal gives me this error. And admin doesn't give me anything, it just kinda resets the line as if I just pressed enter and nothing else.
![cmd_2017-01-11_05-14-00](https://cloud.githubusercontent.com/assets/20447447/21844550/08687a92-d7bd-11e6-9098-eb2be1918f13.png)

**Comment by zductiv** [comment]
I noticed this also on the stable release, but the edge version works fine.

**Comment by Saltystew** [comment]
How buggy is the edge version?

**Comment by Dnkhatri** [comment]
With no update to stable in long time edge is probably better at the moment
