### ISSUE TITLE
AlphaRatio TorrentPotato api returns 0 results

### ISSUE THREAD

**Issue by ghost** [cardigann/cardigann#304]
Searching from within Cardigann returns results, however going to url:

```
OK   http://server:5060/torrentpotato/iptorrents?passkey=xxx&search=the
```

```
FAIL http://server:5060/torrentpotato/alpharatio?passkey=xxx&search=the

{
  "results": [],
  "total_results": 0
}
```
For AlphaRatio the query inside Cardigann seems to be returning category `5030` which is TV...

![cat](https://cloud.githubusercontent.com/assets/25102010/22002521/f4979a90-dc4c-11e6-9ef3-35f4537a4674.png)

> PS: For TorrentLeech the query on the api endpoint doesn't return results from category `100041`

**Comment by lxt2** [comment]
Fixed now
