### ISSUE TITLE
Adding speed.cd

### ISSUE THREAD

**Issue by subzero79** [cardigann/cardigann#31]
This is so far the working yaml, i need to add the rest of the categories.

```
---
  site: speedcd
  name: speed.cd
  description: "TV Series anyone?"
  language: en-us
  links:
    - http://speed.cd/

  caps:
    categories:
      52: TV/HD    #TV/B-Ray
      51: TV/SD    #TV/DVD-R
      2: TV/SD     #TV/Episodes
      49: TV/HD    #TV/HD
      55: TV/Other #TV/Kids
      41: TV/Other #TV/Packs
      50: TV/Sport #TV/Sports
      30: TV/Anime
      1: Movies/Other
      42: Movies
      32: Movies
      43: Movies/HD
      47: Movies
      28: Movies/BluRay
      48: Movies/3D
      40: Movies/DVD
      25: PC/ISO
      39: Console/Wii
      45: Console/PS3
      35: Console
      33: Console/Xbox 360
      46: PC/Phone-Other
      24: PC/0day
      51: PC/Mac
      27: Books
      26: Audio
      44: Audio
      29: Audio/Video



    modes:
      tv-search: [q, season, ep]

  login:
    path: /takeElogin.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
    error:
      - selector: tbody:contains("File Not Found")
    test:
      path: /user/


  search:
    path: /browse.php
    inputs:
      search: "{{ .Query.Keywords }}"
    rows:
      selector: "#torrentTable .boxContent > table tbody tr"
    fields:
      title:
        selector: b:nth-child(1)
      category:
        selector: td:nth-child(1) > div:nth-child(1) > a:nth-child(2)
        attribute: href
        filters:
          - name: querystring
            args: cat
      download:
        selector: td:nth-child(3) > a:nth-child(1)
        attribute: href
      date:
        selector: td.lft > div > span.date > span
        attribute: title
      size:
        selector: td:nth-child(5)
      seeders:
        selector: td:nth-child(6)
      leechers:
        selector: td:nth-child(7)
```

I still don't know how to parse the date

I've tried
```
      date:
        selector: td:nth-child(2) > div:nth-child(1) > span:nth-child(3) > span:nth-child(1)
        attribute: title
```
I think there might be a bug on the last dateparse commits maybe?

The code is 

```
      <span class="date">
         Uploaded 
        <span class="elapsedDate" title="Monday, June 29, 2015 at 3:37am">
          1 year ago
        </span>
```

~~Also the selector changes for seeders/leechers when they are zero. So the parsing gets stucked when seeders or leechers are zero. So I don't what's the approach there.~~ 

I've changed to make it work

```
      seeders:
        selector: td:nth-child(6)
      leechers:
        selector: td:nth-child(7)
```

**Comment by lxt2** [comment]
That date format should be handled by the default date parsing, so you don't need any filters. Could you post the output of the error relating to the date from the `cardigann test --debug definitions/speedcd.yml`?

**Comment by lxt2** [comment]
Btw, I'd be inclined to use a selector like `.elapsedDate` for the date. You were correct about using the title attribute.

**Comment by subzero79** [comment]
During testing with chrome inspector the "copy selector" wasn't working very well the selectors weren't coming. So I switched to firefox which gave me all the selectors I posted including the date. Now back to chrome copy selector for the date gave me this time

```td.lft > div > span.date > span```

I putted it in the yml and now is working ok.

```
      date:
        selector: td.lft > div > span.date > span
        attribute: title
```

I guess you need to add the date as field for web search.

**Comment by lxt2** [comment]
Are you able to submit a pull-request @subzero79? I can help if not, but that is the easiest way to do this.

**Comment by subzero79** [comment]
Yes. I'll fork it and send a PR.

**Comment by lxt2** [comment]
Closed in #36, many thanks.

**Comment by subzero79** [comment]
I am running into a very strange issue. Even if the logs shows all the info parsed correctly the UI search is not displaying the leechers correctly. Look at this log 

https://gist.github.com/subzero79/8260b4c9c810339036f9ad3ec4bd6d0e

And here the screenshot

![screen shot 2016-10-01 at 11 05 19 pm](https://cloud.githubusercontent.com/assets/7058119/19014271/3e752a9e-882c-11e6-939d-b5660fa66fe9.png)

Also I don't know why the seeders numbers are appended to the title, could be a bug ? or something wrong in my definition?

**Comment by mmarquezs** [comment]
I also went crazy with this :P
 But it's not  the leechers it's the total peers look at the title of the column. The leechers are not shown, well it's the peers - seeders.

**Comment by subzero79** [comment]
You're correct is not the leechers column, is peers. Do you get the number also appended to the title ?

**Comment by mmarquezs** [comment]
No and Yes I mean no i don't have the number of leechers appended  to the end of the title. But one of the two trackers I made (HDArea one) it has some weird numbers appended to the title I didn't notice it before but I think know what is it.

**Comment by subzero79** [comment]
What do yo think @lxt2?
