### ISSUE TITLE
Does Cardigann generate RSS feeds or is it just for searching?

### ISSUE THREAD

**Issue by brimur** [cardigann/cardigann#315]
Does anyone know if Cardigann generate an RSS feeds? Using it with Sonarr, I added it as a custom torznab and it says RSS and Search are enabled. However while it will always find a file when I do a search Sonarr never grabs any file from the RSS feed like it does with other RSS feeds. So I wonder is it for searching only or should I be seeing an RSS feed too?

I had the same issue with Jackett public btw

**Comment by jackusm** [comment]
Did you find out?

**Comment by kaso17** [comment]
The torznab feed generated by cardigann or jackett are RSS feeds with extra attributes. They should work as standard feeds too.
