### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by foXaCe** [cardigann/cardigann#323]
Hello,

Why the docker version do no have all indexeurs ?

**Comment by kkuhle** [comment]
I was just noticing this as well.  It would be nice to be able to use some of the trackers that have been added so I don't have to use jackett and cardigann.  I'm guessing the reason for this is that we are some versions back.  Not sure who is responsible for maintaining the docker release but it would be awesome if we could get an update!

**Comment by Dnkhatri** [comment]
The guy that made the newest release made a mistake so the new definitions
were not added inside the binary has posted a patch will be fixed in the
next relese

**Comment by kkuhle** [comment]
Thanks for the info.  I will look forward to the next release then!

**Comment by foXaCe** [comment]
thanks for the info

**Comment by hotio** [comment]
docker pull hotio/cardigann gives you latest version

https://github.com/hotio/docker-cardigann/blob/master/Dockerfile

**Comment by foXaCe** [comment]
thanks

**Comment by kkuhle** [comment]
I've pulled the latest and created a fresh cardigann docker. It now says version 1.9.8.  However it is still missing trackers that say are supported on the GitHub page. I'm wondering if the definitions still need to be fixed like Dnkhatri said. In think I read that this should be done in 1.9.9. Hopefully we'll see the fixes there with the definition update.

**Comment by hotio** [comment]
In half an hour do another pull just started rebuild on commit f717153e22950f8632ac920bb90b0e098037683e if it's not in there, don't know

**Comment by hotio** [comment]
Try now

**Comment by kkuhle** [comment]
Woohoo!  Latest version has what I'm looking for!  Thanks for getting that up their so quickly hotio.
