### ISSUE TITLE
[ Radarr Support ] Add movie search caps and params

### ISSUE THREAD

**Issue by onedr0p** [cardigann/cardigann#327]
This is a standard part of the nzb indexer caps...

```xml
<caps>
	<searching>
		<search available="yes" supportedParams="q"></search>
		<tv-search available="yes" supportedParams="q,season,ep,tvdbid,tvmazeid,rid"></tv-search>
	</searching>
	<categories>
		<category id="2040" name="Movies/HD"></category>
	</categories>
</caps>
```

Please add: 
```xml
<movie-search available="yes" supportedParams="q,imdbid"></movie-search>
```
under:
```xml
<tv-search available="yes" supportedParams="q,season,ep,tvdbid,tvmazeid,rid"></tv-search>
```

Thanks!

**Comment by howsTricks** [comment]
Very interested in this!

**Comment by scambra** [comment]
+1

**Comment by howsTricks** [comment]
Looks like it does support <movie-search... . The reason it wasn't working for me was the result of my definition file not including the categories for movies (2030 for example).

**Comment by kaso17** [comment]
cardigann doesn't support movie-search, Radarr just falls back to standard search (no support for searching by imdb, etc.).

**Comment by sco01** [comment]
+1

**Comment by froman753** [comment]
+1

**Comment by Aesculapius** [comment]
+1

**Comment by Koxx3** [comment]
+1

**Comment by pmettraux** [comment]
+1

**Comment by lxt2** [comment]
Ok cool, I will look at this. Fixing IMDB first though.

**Comment by lxt2** [comment]
Ok this is done.

**Comment by rafacapa** [comment]
Now you can add as Torznab correctly but when executing any search from Radarr it doesn't respond with any results.
