### ISSUE TITLE
Bug report: [Status Code 503 received from IMDB]

### ISSUE THREAD

**Issue by vacon04** [cardigann/cardigann#332]
### Issue experienced

I seem to be having problems with radarr and cardigann. When trying to look for a certain movie I get the error "Status Code 503 received from IMDB"
The problem seems to be happening only with certain movies (mainly older ones) so I don't know if this is a problem with imdb or cardigann or both.

### Steps to reproduce

When looking for a movie with radarr I end up getting no results from the trackers that I have in cardigann. When using the url "http://192.168.0.12:5060/torrentpotato/thepiratebay?passkey=(removed)&user=&imdbid=tt1800302 I get the error code that I just mentioned. If I try with another movie such as tt3783958 (La la land) everything seems to work fine.

### Cardigann version (in the footer, or via `cardigann --version`)

Cardigann version 1.9.9

**Comment by lxt2** [comment]
Should be fixed in master
