### ISSUE TITLE
Freshon doesn't work

### ISSUE THREAD

**Issue by gcamp** [cardigann/cardigann#343]
When testing Freshon, I get the following error : 

```
An error occurred
No working urls found
```

**Comment by gcamp** [comment]
Other trackers are working well

**Comment by Kewjoe** [comment]
It's working fine for me. What URL are you using?

**Comment by gcamp** [comment]
http://freshon.tv/

The error has changed, it's now `No input found with name 'username'.`

**Comment by Kewjoe** [comment]
I'm using "https://freshon.tv/"  and it works. try adding the 's'

**Comment by gcamp** [comment]
Same error unfortunately

**Comment by lxt2** [comment]
I believe they have shut down, so closing this.
