### ISSUE TITLE
T411 indexers returning too many results

### ISSUE THREAD

**Issue by foux** [cardigann/cardigann#344]
Hi there,

Using T411 indexer on TV shows, it returns too many results.
With the query : 
`time="2017-02-09T08:19:13Z" level=info msg="Searching indexer" query="apikey=r̶e̶d̶a̶c̶t̶e̶d̶&cat=5030%2C5040&ep=15&extended=1&limit=100&rid=28304&season=6&series=New+Girl&t=tvsearch&tvdbid=0&tvmazeid=58" site=t411`
the indexer returns episodes form all seasons, and of any episodes, not only from season 6 episode 15.

Am I missing something?

Thanks

**Comment by JigSawFr** [comment]
No, it's not your fault, T411's search engine is a pain.
It's hard to actually get only episodes of series we want,
We need to map every t411 search engine options to get only revelant results.
Nowdays, index is just searching with basic options.

**Comment by foux** [comment]
Indeed, if I'm looking at https://github.com/KiLMaN/T411-Torznab , the way he construct its search terms is a real pain...

**Comment by kaso17** [comment]
That proxy seems to use an proper API. The definition is currently using the normal web search.
according to their FAQ https://www.t411.li/faq/#300 it should be possible to use modifiers like + and & to improve the search. I tried e.g. `"New Girl" + S06E15` but it doesn't seem to work. Do you have a working example for the normal web search URL which returns the expected results?

**Comment by foux** [comment]
I've got one here, but it doesn't really help : http://www.t411.li/torrents/search/?name=new+girl&description=&file=&user=&cat=210&subcat=433&term%5B46%5D%5B%5D=952&term%5B45%5D%5B%5D=973&search=%40name+new+girl+&submit=Recherche

This URL forces us to retrieve the terms from the API unfortunately

**Comment by kaso17** [comment]
It should be possible to do the season/episode <> term mapping with a lot of if conditions in the definition search/inputs/raw option:
For each season: `{{if eq .Query.Season \"1\"}}&term[45][]=968{{end}}`
For each episode: `{{if eq .Query.Ep \"1\"}}&term[46][]=937{{end}}`

**Comment by JigSawFr** [comment]
@kaso17 yes it's possible in this way, but there will be a huge amount of conditions, no ?
I don't if is it possible to use an array to make association of parameters and numbers.

**Comment by kaso17** [comment]
yes, plenty of conditions, but there's no other way I can think of with the golang text/template engine.

**Comment by flightlevel** [comment]
Hi @JigSawFr If you search via the API like Jackett was doing in the past, does it give you more control of the results?

**Comment by kaso17** [comment]
yes, for Jackett I'm planning to replace the definition with the previous c# implementation and adding support for season/episode terms

**Comment by kaso17** [comment]
In Jackett the definition has been replaced with a native implementation handling the terms for tv-search.
https://github.com/Jackett/Jackett/commit/ece8d524dee1a2947f88bbeaa7a118ec6fb863cb

**Comment by foux** [comment]
Wow, that's great @kaso17, thanks, I'll try that tomorrow.

Just a question, for the category, why do you force the category on TVShow instead of using those supplied by the user?

Thanks again for your work!

**Comment by kaso17** [comment]
The user could potentially supply multiple categories but T411 seems to support only signal category searches. Which one should be choosen in this case? We would have to do multiple queries. I think back when I tested it didn't support searching terms without category. That's why I hard coded TV Shows for tv-search. Is there any other category supporting the same episode/season terms?

**Comment by ldexterldesign** [comment]
https://torrentfreak.com/t411-frances-most-visited-torrent-site-has-disappeared-170627/ - T411 has gone

Unless someone has another URL this can be deleted from Cardigann

Regards

**Comment by toxic0berliner** [comment]
t411.si is still going strong, in fact, it's a new tracker, public now instead of previously private t411.
I hope the code in cardigann will work with this new t411.si but I doubt it. I'm in the process of installing sonarr & radarr on my raspberry to offload my synology nas, will report here if I manage to do it and see if cardigann can handle this new t411.

**Comment by lxt2** [comment]
@toxic0berliner could you file a new tracker issue when you check? I'll close this for now.

**Comment by toxic0berliner** [comment]
Sorry to report that I've gotten my jackett setup running smooth (now that I'm not out of ram on my box it justs works) so I won't be doing the switch to cardigan until I start getting issues with jackett again... Might be a while. 
So I will not be opening a new issue to give better reports.
But before I leave here, let me say I'm using t411v2 on jackett on a daily basis. t411.si is indeed going strong, but it's a brand new website and the old indexer will most probably not work anymore. You should definitively look into adding support for it to cardigan (might even bring me back someday :D)

Sorry I couldn't be of more help, time is a scarse resource here...

Best of luck with cardigan, crossing fingers for you guys !

**Comment by ldexterldesign** [comment]
@toxic0berliner hey, http://t411.si not working for me - what's the new URL? Yours hopefully.
