### ISSUE TITLE
Feature: Request: Enable Github wiki

### ISSUE THREAD

**Issue by ninovanhooff** [cardigann/cardigann#350]
I'd like to write a totorial on how to use Cardigann with Couchpotato.

This may seem straightforward, but I had no clue that the username could be left empty, and that Couchpotato fails to request the url without the http:// prefix, for example

**Comment by kaso17** [comment]
Unfortunately the owner of the project @lxt2 disappeared and I've no access to the settings.

**Comment by tuefekci** [comment]
@ninovanhooff even without the wiki you still can push a md file into the docs folder if kaso17 merges it into the main readme people will find it and its displayed nice.

**Comment by lxt2** [comment]
I'm back :) My preference is to keep docs in the docs folder, but we'd welcome contributions @ninovanhooff
