### ISSUE TITLE
Feature request: manual / user added trackers

### ISSUE THREAD

**Issue by danpowpow** [cardigann/cardigann#352]
### Description of feature/enhancement
rather than add tracker requests to the github for emerging/changing trackers, add a method for users to add their own. 

### Justification
all the unfulfilled tracker requests filling up the github

### Example use case
Add indexer > manual add

Am I missing something? does the definitions file basically provide this function?

**Comment by kaso17** [comment]
You just have to write a definition file and put it into the correct directory (see readme for directories)

**Comment by danpowpow** [comment]
@kaso17 - thanks!
