### ISSUE TITLE
Bug report: LINUX .config folder created at / when run as background process

### ISSUE THREAD

**Issue by ozoak** [cardigann/cardigann#353]
A .config/cardigann/ folder path is created rather than referencing the user home folder path when run as a background process. eg: "cardigann service start" will create the folder /.config/cardigann/ and generate a config.json file in that folder, but when run as a foreground process it uses the folder in the home path eg: "cardigann service run" will use /root/.config/cardigann/config.json. This also impacts any other files referenced from the .config/cardigann/ location (eg: yml files in a nested "definitions" folder).

Tested with 1.9.9-12-gceb1945

ed: I'm happy to contribute and try and fix it, but I'm 23 hours into my day and my brain is aching :)

**Comment by lxt2** [comment]
Closing because this is very old, please re-open if you are still using!
