### ISSUE TITLE
Indexer Request: AnimeBytes, Animetorrents, Nyaa

### ISSUE THREAD

**Issue by SilverSix311** [cardigann/cardigann#356]
### Indexer Name
http://animetorrents.me/
https://animebytes.tv/
https://www.nyaa.se/
### Is the indexer private or public? If private, can you provide an invite?
Animetorrents.me - Private - Can provide Invite
Animebytes.tv - Private - Cannot currently provide Invite
Nyaa.se - Public
### Indexer URL
http://animetorrents.me/
https://animebytes.tv/
https://www.nyaa.se/
### Indexer language
All are english

**Comment by Cocotus** [comment]
+1 for Nyaa! Its the best for animes

**Comment by boran73100** [comment]
Nyaa.si would be amazing since they are mostly filling the gap left by the old Nyaa. Any plans for that?

**Comment by itschrisonline** [comment]
+1 for Nyaa
and animetorrents is open
https://animetorrents.me
