### ISSUE TITLE
TorrentLeech (other trackers) test fails

### ISSUE THREAD

**Issue by MoinFaraz** [cardigann/cardigann#357]
I'm a new user. I've added Torrent leech, supplied username/password and saved. But, it keeps on showing 'failed' when I test it. I'm wondering where am I suppose to see error logs or something similar to find out what's going on? BTW; Torrent leech isn't the only tracker that I've tried. Others failed too. I'm confused?

![error](https://cloud.githubusercontent.com/assets/13995057/23097024/96c237fa-f64f-11e6-8043-d6698a3dbec6.png)

The following trackers have failed:

- Torrentleech
- Torrentbytes
- Speed.cd

**Comment by lxt2** [comment]
We've fixed several TorrentLeech issues, could you please re-open if you are still having an issue?
