### ISSUE TITLE
Bug: AlphaRatio not working

### ISSUE THREAD

**Issue by dennisrpnw** [cardigann/cardigann#360]
Hey, I can't add AlphaRatio. I get the following error:

"An error occurred

Form not found matching expr 'form'."

**Comment by TerrorFactor** [comment]
I also have issues with Alpharatio. Testing fails, "no input found with name 'username'. Weirdly enough, if you use the search, it does return results.

**Comment by benj3** [comment]
Also receiving this error

**Comment by jlongton** [comment]
Same here.  Seemed to work for a little while after uninstalling and reinstalling on QNAP.

**Comment by kaso17** [comment]
please try updating to jackett v0.7.1469

**Comment by lxt2** [comment]
Should be fixed now!
