### ISSUE TITLE
Bug in version 1.9.10

### ISSUE THREAD

**Issue by Itzak613** [cardigann/cardigann#366]
Cardigann running on windows and saves config that survives reboot.   However can't find the config.json file in AppData\Local or roaming either.  Where the heck is it?   Ran a search of c drive for config.json and its not anywhere

**Comment by kaso17** [comment]
Try C:\ProgramData\Jackett

**Comment by Itzak613** [comment]
It's not there either or anywhere in \ProgramData  in fact a search of C: drive does not find config.json

**Comment by kailan** [comment]
I had this issue too, I was running cardigann on macOS for ages but never found the config file 🤔

**Comment by kaso17** [comment]
Please ignore my previous comment.
If you're running it as service your users AppData is likely not the same as the services user appdata directory. You might not have permission to access the system appdata directory (resulting in on search results).
On unix (macos?) there was a bug causing the config to be stored directly in the rood directory (/.config or /cardigann). Not sure about it.

**Comment by Itzak613** [comment]
Still have not found it.  Have hidden file view enabled.  I'm on windows,
 starting to wonder if it's in the registry.



זו ארצנו
אין עוד מלבדו
* ​יצחק*

**Comment by ozoak** [comment]
kaso17 has it - when installed as a service cardigann.exe runs as SYSTEM.
The config.json file will be found in C:\Windows\System32\config\systemprofile\AppData\Roaming\cardigann\

Not unheard of, a few other things lean on that location. Will need to provide your user account rights to the folder to save manual changes from there, but should be able to access the path via powershell/cmd.

**Comment by Itzak613** [comment]
Thank you !!! That was it.

C:\Windows\System32\config\systemprofile\AppData\Roaming\cardigann



זו ארצנו
אין עוד מלבדו
* ​יצחק*
