### ISSUE TITLE
Indexer Request: en.Metal-Tracker.com

### ISSUE THREAD

**Issue by joelstitch** [cardigann/cardigann#375]
### Indexer language: English trough en.metal-tracker.com and russian trough www.metal-tracker.com

I tried making the YML but am learning as I go and could not get Cardigann to work with it. I always get the error "Indexer not Found"

This is what I got so far:

`  site: metal
  type: semi-private
  name: metaltracker
  language: ru-ru
  encoding: UTF-8

  links:
    - http://www.metal-tracker.com/
    - http://en.metal-tracker.com/

  caps:
    categories:
      16: Audio

    modes:
      search: [q]

  login:
    path: /user/login.html
    form: "form"

    inputs:
      UserLogin[username]: "{{ .Config.username }}"
      UserLogin[password]: "{{ .Config.password }}"

    error:
      - path: /user/login.html

        message:
          selector: "#login_error"

    test:
      path: /user/login.html

  ratio:
    text: "0"

  search:

    path: /torrents/search.html

    inputs:

       $raw: 'search={{replace .Keywords " " "*" -1}}'

    rows:

      selector: "table.t_table tr:nth-child(n + 3)"

    fields:

      download:

        selector: "td:nth-child(1) a[href*='d.php']"

        attribute: href

      category:

        text: "16"

      title:

        selector: "td:nth-child(2)"

      details:

        selector: "td:nth-child(2) a"

        attribute: href

      size:

        selector: "td:nth-child(3)"

      date:

        selector: "td:nth-child(4)"

      seeders:

        selector: "td:nth-child(5)"

      #leechers:

        #selector: "td:nth-child(6)"

      downloadvolumefactor:

        text: "0"

      uploadvolumefactor:

        text: "1"
`

**Comment by kaso17** [comment]
the dash in the "site" attribute might cause your problem.

**Comment by joelstitch** [comment]
That fixed the error but now I get the error "Failed to match selector "#login_error""

**Comment by kaso17** [comment]
Try 
```yaml
error:
       - selector: #login_error
```

**Comment by joelstitch** [comment]
still the same error. This is what the logs give me:

`→ Testing indexer metaltracker at http://en.metal-tracker.com
  Testing required config is available SUCCESS ✓ in 357.161µs
  Testing login with valid credentials FAILURE ✗ in 5.539926655s
→ Indexer metaltracker FAILED with Failed to match selector "#login_error"
time="2017-05-07T13:55:59Z" level=error msg="Failed to login" error="Failed to match selector \"#login_error\"" site=metaltracker 
time="2017-05-07T13:55:59Z" level=error msg="Test failed" error="Failed to match selector \"#login_error\"" 
`

**Comment by joelstitch** [comment]
I also can't find anything about login_error on the login page source so im not sure if that's what should go on the error section. I'm learning this as I go so might have done it wrong.

**Comment by kaso17** [comment]
See https://github.com/Jackett/Jackett/wiki/Definition-format for some details (many features are missing from cardigann)
You can just remove the error section if you're unsure.

**Comment by joelstitch** [comment]
So I got it to pass the test now with these results:

`→ Indexer metal is OK

time="2017-05-09T03:43:45Z" level=info msg="Searching indexer" query="apikey=r̶e̶d̶a̶c̶t̶e̶d̶&q=slayer&t=search" site=metal 
time="2017-05-09T03:43:45Z" level=info msg="Query returned 0 results" site=metal time=170.944939ms 
time="2017-05-09T03:45:03Z" level=info msg="Unknown indexer \"metaltracker\" in configuration" 
time="2017-05-09T03:45:04Z" level=info msg="Unknown indexer \"metaltracker\" in configuration" 
time="2017-05-09T03:45:26Z" level=info msg="Unknown indexer \"metaltracker\" in configuration" 
→ Testing indexer metal at http://en.metal-tracker.com/
`
But when I try to search for something I get no results and get these logs:

`time="2017-05-09T03:49:42Z" level=info msg="Searching indexer" query="apikey=r̶e̶d̶a̶c̶t̶e̶d̶&q=metallica&t=search" site=metal

time="2017-05-09T03:49:42Z" level=info msg="Query returned 0 results" site=metal 
time=168.790359ms `

**Comment by kaso17** [comment]
unfortunately the test can be easily fooled (no results=pass). Most likely you rows selector is incorrect returning no rows at all.

**Comment by mirwan** [comment]
@joelstitch I don't if things have changed with the definition since the last comments.
Based on Jackett definition and your work (especially on inputs!) I managed to have it work - a query with "metallica" returns expected results.
I proposed a PR with the updated definition, I hope it helps
