### ISSUE TITLE
Filelist indexer now working

### ISSUE THREAD

**Issue by dragosmiron** [cardigann/cardigann#376]
hello.
I believe the filelist indexer is broken.
Is returning back a list of images for the torrent rather than the torrent itself.
Sonarr is not working with it because of that, for good reason.

**Comment by kaso17** [comment]
It's working fine for me. Please provide logs.

**Comment by kaso17** [comment]
never mind, I used jackett instead of cardigann. Don't know about the status in cardigann.

**Comment by dragosmiron** [comment]
the diff btw jacket and cardigann is that cardigann has no support.

**Comment by lxt2** [comment]
Cool story @dragosmiron.

**Comment by dragosmiron** [comment]
closed because??? it was fixed by itself?

**Comment by dragosmiron** [comment]
@lxt2
