### ISSUE TITLE
Status Code 401 received from IMDB

### ISSUE THREAD

**Issue by brimur** [cardigann/cardigann#377]
I've been getting this error for the past week. Before that Cardigann worked great. I had been using torrentpotato with Radarr. Now, in Radarr I get no results and the filtering error...

''''
HTTP Error - Res: [GET] http://localhost:5060/torrentpotato/thepiratebay?passkey=(removed)&user=&imdbid=tt0167260: 502.BadGateway
{
  "error": "Status Code 401 received from IMDB"
}
''''

Also seeing these errors
[http://i.imgur.com/Sx8QQQF.png](http://i.imgur.com/Sx8QQQF.png)

 If I do a test search on Cardigann it will return results.

**Comment by vandammesander** [comment]
I am having the same issue. Search is working but the imdbid is not. I am getting the same result code (502) & message as you are ("error": "Status Code 401 received from IMDB").

**Comment by subzero79** [comment]
Jackett suffers from this also, the omdb api has gone into private. cardigann uses gomdb which relies on omdb api. Torrentpotato api search is dead in cardigann if someone doesn't change it how it queries the title using the imdbid. The project is currently not maintained, so i see no fix to this one.

**Comment by brimur** [comment]
Latest version of Jackett works great and is a replacement for Cardigann

**Comment by lxt2** [comment]
I'll look into this.

**Comment by subzero79** [comment]
@lxt2 though you weren't coming back, good to hear from you. If this helps for example i hold my own imdb api query daemon (is a scraper), i use this for getting imdb ratings for processing quality of radarr movies.
Is python code from here https://github.com/bkvirendra/imdb-scraper, i added the feature of returning the rating. But basically you send the imdbid and it returns a json with several information for the movie.

**Comment by lxt2** [comment]
Fixed in https://github.com/cardigann/cardigann/pull/385
