### ISSUE TITLE
No answer from Cardigann when using TorrentPotato in CouchPotato (dev version)

### ISSUE THREAD

**Issue by Katawann** [cardigann/cardigann#378]
### Issue experienced
No answer from Cardigann when using TorrentPotato in CouchPotato

### Steps to reproduce
If I do a request for the movie Kingsman  from CouchPotato, I get the following message (example with T411 as indexer, but didn't work for all others indexers and movies I tried):

- in CouchPotato:
 > 05-30 20:16:44 INFO [hpotato.core.plugins.base] Opening url: get http://192.168.1.185:5060/torrentpotato/t411?imdbid=tt4649466&search=Kingsman%3A+The+Golden+Circle+2017&user=Katawan&passkey=xxx
05-30 20:16:45 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://192.168.1.185:5060/torrentpotato/t411?imdbid=tt4649466&search=Kingsman%3A+The+Golden+Circle+2017&user=Katawan&passkey=xxx&search=Kingsman%3A+The+Golden+Circle+2017&user=Katawan&passkey=xxx
05-30 20:16:44 DEBUG
[hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last): HTTPError: 502 Server Error: Bad Gateway for url: http://192.168.1.185:5060/torrentpotato/t411?imdbid=tt4649466&search=Kingsman%3A+The+Golden+Circle+2017&user=Katawan&passkey=xxx
05-30 20:16:44DEBUG
[hpotato.core.plugins.base] Waiting for TorrentPotato, 1 seconds

- in Cardigann for the corresponding request:

> DEBU[0026] GET /torrentpotato/t411?imdbid=tt4649466&search=Kingsman%3A+The+Golden+Circle+2017&user=Katawan&passkey=ff63b4e41fda247f6578f76800565dd6 method=GET path=/torrentpotato/t411?imdbid=tt4649466&search=Kingsman%3A+The+Golden+Circle+2017&user=Katawan&passkey=ff63b4e41fda247f6578f76800565dd6 remote=192.168.1.173:40100
 
And then nothing happen... I guess that normally it should start to search for the movie. Also if I search from Cardigann, it works perfectly (but it uses Torznab).

### Cardigann version
dev

**Comment by lxt2** [comment]
This should be working after 1.10.
