### ISSUE TITLE
FR: Open vs Closed trackers

### ISSUE THREAD

**Issue by mgaulton** [cardigann/cardigann#382]
i'd love to see all the Open trackers added by default or at least, have the list of trackers on the documentation indicate. Makes picking and choosing easier for novices.

**Comment by lxt2** [comment]
Let's start with updating the docs to split between Open and Closed trackers along the lines of what https://github.com/Jackett/Jackett has in it's README. Any chance you'd assist with that @mgaulton?

**Comment by mgaulton** [comment]
This is what I have.

Supported Public
KickAssTorrent
ThePirateBay (TPB)
Torrentz2
AvistaZ
EZTV
HDME

Supported Private
Abnormal
AlphaRatio
Apollo (XANAX)
BIT-HDTV
BitMeTV
Blu-bits
BeyondHD
CinemaZ
DanishBits
Demonoid
EoT-Forum
Ethor.net (Thor's Land)
FileList
FunFile
HD-Torrents
Immortalseed
IPTorrents
MoreThanTV
MySpleen
NCore
NetHD
Norbits
PreToMe
PrivateHD
Redacted
Speed.CD
Sceneaccess
SceneTime
Shareisland
The New Retro
The Shinning
Torrent Sector Crew
Torrent-Syndikat
Torrentbytes
TorrentDay
TorrentHeaven
Torrentleech
ToTheGlory
UHDBits
WorldOfP2P
Xthor
Transmithe.Net
Tspate

Unsorted
AlphaReign <- dead/dying?
Freshon <- dead 
HDArea <- dead
Torrent411 (T411) <- dead

**Comment by lxt2** [comment]
Done! Thanks!

**Comment by ldexterldesign** [comment]
@lxt2 https://docs.google.com/spreadsheets/d/1WZ3RS3HA7tdRqMU2PXPEUYWGqrG1TnnguEJ6NbWJa-A - this should be useful in future

Regards

**Comment by TuRDMaN** [comment]
Just came here to request this. Looks like it hasn't been implemented yet.
