### ISSUE TITLE
Cardigann TorrentDay Error

### ISSUE THREAD

**Issue by Gothamen** [cardigann/cardigann#390]
Hi All,

Newly experienced issue with communication between Cardigann and TorrentDay, was working up until mid last week then noticed an indexer error on Sonarr, receiving the below now when i try to Test the communication between Cardigann and TorrentDay. Originally on Cardigann version 1.9.10, updated to 1.9.12 and issue remains.

_→ Testing indexer torrentday at http://td-update.com/
  Testing required config is available ←[32mSUCCESS √←[0m ←[37min 1.0015ms←[0m
  Testing login with valid credentials ←[32mSUCCESS √←[0m ←[37min 8.066765s←[0m
  Testing search mode "search" time="2017-08-20T21:00:27+10:00" level=info msg="
Searching indexer" query="limit=3&t=search" site=torrentday
time="2017-08-20T21:00:28+10:00" level=warning msg="Row #1 has unparseable seede
rs value \"814 MB\" in seeders" site=torrentday
time="2017-08-20T21:00:28+10:00" level=warning msg="Row #2 has unparseable seede
rs value \"6.65 GB\" in seeders" site=torrentday
time="2017-08-20T21:00:28+10:00" level=warning msg="Row #3 has unparseable seede
rs value \"436 MB\" in seeders" site=torrentday
time="2017-08-20T21:00:28+10:00" level=info msg="Query returned 3 results" site=
torrentday time=958.6009ms
←[31mFAILURE ?←[0m ←[37min 6.1090005s←[0m
→ Indexer torrentday ←[31mFAILED←[0m with ←[31mResult row 1 has zero size←[0m
time="2017-08-20T21:00:28+10:00" level=error msg="Test failed" error="Result row
 1 has zero size"_

Have tried changing the TorrentDay website to torrentday.com and torrentday.it etc, no change in response.

**Comment by sadsturbator** [comment]
I am also having the same issue. URL and cookie is correct. Wondering if it's an issue on their end?

**Comment by thamilton91** [comment]
Same here.

**Comment by thamilton91** [comment]
Anyone have an update on this?

**Comment by lxt2** [comment]
If someone wants to send me an invite to rznqsp8ffyeprn2l@gmail.com I will fix it.

**Comment by ek250** [comment]
@lxt2  Invite sent.

**Comment by thamilton91** [comment]
@lxt2 any word on this?
