### ISSUE TITLE
Indexer Request: Torrentbytes

### ISSUE THREAD

**Issue by ldexterldesign** [cardigann/cardigann#397]
### Indexer Name

Torrentbytes

### Is the indexer private or public? If private, can you provide an invite?

Private, but open registration. Can provide invite otherwise.

### Indexer URL

http://torrentbytes.net

### Indexer language

English

--

Hey all,

Hope you're well

Thanks for software

Can we get this fixed?:

```
→ Testing indexer torrentbytes at http://www.torrentbytes.net/
  Testing required config is available SUCCESS ✓ in 468.032µs
  Testing login with valid credentials SUCCESS ✓ in 2.922688088s
  Testing search mode "search" ERRO[0028] Filling input failed    error=No input found with name 'username'. site=torrentbytes
ERRO[0028] Login failed    error=No input found with name 'username'. site=torrentbytes
FAILURE ✗ in 2.130745658s
→ Indexer torrentbytes FAILED with No input found with name 'username'.
ERRO[0028] Test failed     error=No input found with name 'username'.

ERRO[0503] Filling input failed    error=No input found with name 'username'. site=torrentbytes
ERRO[0503] Login    error=No input found with name 'username'. site=torrentbytes
```

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Yours faithfully

Related:

2016-10-06 https://github.com/cardigann/cardigann/issues/81
2016-11-16 https://github.com/cardigann/cardigann/issues/220
2017-02-18 https://github.com/cardigann/cardigann/issues/357

**Comment by lxt2** [comment]
This seems related to a redirect from http://www.torrentbytes.net/ to https://torrentbytes.net/. If you update the url in the config, it will work. I'll figure out the best way to fix this globally.

**Comment by ldexterldesign** [comment]
I got it working:

```
→ Testing indexer torrentbytes at http://www.torrentbytes.net/
  Testing required config is available SUCCESS ✓ in 509.205µs
  Testing login with valid credentials SUCCESS ✓ in 3.076165388s
  Testing search mode "search" INFO[0010] Searching indexer                             query=limit=3&t=search site=torrentbytes
INFO[0010] Query returned 0 results                      site=torrentbytes time=610.289037ms
SUCCESS ✓ in 1.128211992s
  Testing search mode "tv-search" INFO[0011] Searching indexer                             query=cat=5040%2C5030&limit=3&t=tv-search site=torrentbytes
INFO[0011] Query returned 0 results                      site=torrentbytes time=627.199794ms
SUCCESS ✓ in 1.235776926s
  Testing empty results are handled INFO[0012] Searching indexer                             query=series=nothingshouldmatchtheseresults&t=search site=torrentbytes
INFO[0012] Query returned 0 results                      site=torrentbytes time=554.409854ms
SUCCESS ✓ in 1.041004397s
  Testing ratio SUCCESS ✓ in 11.159µs
→ Indexer torrentbytes is OK
```

Strangely I added the exact URL the website renders (i.e. https://torrentbytes.net/ ) into the UI, which is reflected in my ``config.json``, yet the CLI throws out http://www.torrentbytes.net/ (see above) - what's happening here?

NB I restarted CLI - no difference

Kind thanks

**Comment by lxt2** [comment]
The logic for which url to use is confusing and flawed. The cli will list the first working url from the links in the definition, but the url used is from the config.

**Comment by ldexterldesign** [comment]
Thanks for reply

Ahh, glad I'm not going crazy

If I spot issues like this in future should I pull request the definition?

Are the definitions what populate the UI form select?

Cheers

**Comment by lxt2** [comment]
Yeah, that would be great. Yup, the `link` block is used to populate the UI form select.

**Comment by lxt2** [comment]
Fixed in master.
