### ISSUE TITLE
Indexer Request: YggTorrent & Custom

### ISSUE THREAD

**Issue by pedrolti0** [cardigann/cardigann#403]
Hi dev',

Since few days T411.si is not available.
It's now merge to another indexer : https://yggtorrent.com

Could you add it on Cardigann.

By the way, is it possible to add an entry to put custom indexer manually ?
I've tried to manually add one in config file, but without sucess.

Thanks in advance.

**Comment by mirwan** [comment]
Hi, just added a yml definition for yggtorrent. It has not been fully tested but...

To add a custom definition, just add your yml file in a "definitions" sub-folder of the cardigann config folder (e.g. I added mine under /etc/cardigann/definitions but it may depend on your setup.

**Comment by Danelem** [comment]
@mirwan it worked well until Yesterday. I think they changed some links.

**Comment by pedrolti0** [comment]
Yes they've update the URL.
You can correct it easily.

Open the .yml file
And replace all "https://yggtorrent.com" by "https://ww1.yggtorrent.com"

I've done that, and now it's working good again ;)

I'm going to check if i can update the github file.

**Comment by mirwan** [comment]
Actually, simply replacing the URL doesn't do the trick (test-definition fails).
The download link is not part of the search results anymore BUT the download id is part of the URL of the torrent page and thus can be used to calculate the download link.
It's a bit late now for me to jump into css selectors to fix it but will do tomorrow (maybe I'll try one the way to refactor a bit in order to use the config URL instead of hardcoded ones).

**Comment by mirwan** [comment]
Just updated my PR with updated default FQDN and refactoring in order not to depend on the URL.
Let me know if anything's still wrong.

BTW I don't know anything about the approval process of the PR, maybe a like/+1 or two could help maintainers to merge it faster (?!?).

**Comment by aolwas** [comment]
+1

works well with sonarr.
should work with radarr but have the #399 issue

**Comment by Danelem** [comment]
@mirwan Thanks for that. I'm using it with SickRage, but I think that line 138 should be path: "{{if .Query.Keywords}}/engine/search?q={{ .Keywords}}{{else}}/torrents/**today**{{end}}" so we get the last torrents uploaded.
