### ISSUE TITLE
Error trying to install 1.70 Linux

### ISSUE THREAD

**Issue by Dnkhatri** [cardigann/cardigann#43]
Hi I am getting an error trying to install using the cmd line install that is on the website. Extracting the file and running like previous versions is fine.

**Comment by lxt2** [comment]
You are correct, I haven't updated that doc to reflect the new release location! Will fix.

**Comment by lxt2** [comment]
Fixed in 9fc652f0f8c09604bdbb396ba33baa6a9c10345c.
