### ISSUE TITLE
Feature request: Restart Button on Web Interface

### ISSUE THREAD

**Issue by jun6lee** [cardigann/cardigann#431]
Once a week or so, I do find a restart needed for certain indexers that appear to show errors in sonarr, which is far from unreasonable. However, I've got it installed on a QNAP NAS where it can be quite fiddly for non-techies to log into the NAS interface to stop and start the service.

It would be great to have a restart button on the web ui for simpler use for the family in my absence.

**Comment by lxt2** [comment]
Hmmm, would be good to figure out what the errors are and fix them! Does the restart fix them @jun6lee?
