### ISSUE TITLE
Bug in version 1.10.1 while testing TorrentDay the following error message occurs An error occurred Failed to match selector "td.seedersInfo0"

### ISSUE THREAD

**Issue by pcliff069** [cardigann/cardigann#432]
While attempting to contact TorrentDay the folling error occurs
An error occurred
Failed to match selector "td.seedersInfo0"

**Comment by LOLobo21** [comment]
Was looking to see if there may be any updates to this issue?

**Comment by pcliff069** [comment]
none - they seem to have lost interest - have moved to Jackett

**Comment by LOLobo21** [comment]
Yeah Jackett doesn't have way to interface with a bash script, unlike cardigann.

**Comment by pcliff069** [comment]
but unlike Cardigann it works
