### ISSUE TITLE
YGGTorrent DNS Update

### ISSUE THREAD

**Issue by pedrolti0** [cardigann/cardigann#434]
Hello guys,

A new update has come for YggTorrent definition.
I've tried to get the Jackett update but it doesn't work.
https://github.com/Jackett/Jackett/blob/8b861467153831c356d1cd54f79e5dac79f3f772/src/Jackett.Common/Definitions/yggtorrent.yml

Error message at the login step.
No input found with name 'submit'.

Log : 
Testing login with valid credentials [31mERRO[0m[0505] Filling input failed                          [31merror[0m=No input found with name 'submit'. [31msite[0m=yggtorrent | stdout

Could you update this file and if it's possible explain quickly how to know what's wrong ?

Thanks in advance.

**Comment by mirwan** [comment]
@pedrolti0 The current yggtorrent URL (i.e. https://ww4.yggtorrent.is at the moment) must be set in the URL configuration field of the indexer.
Anyway, the indexer definition is broken due to a change in size units (PR #435 should fix this).

**Comment by pedrolti0** [comment]
Thx for your actions @mirwan ;)
