### ISSUE TITLE
Request for Trackers TorrentDay, Torrentleech and PrivateHD

### ISSUE THREAD

**Issue by theCheek** [cardigann/cardigann#44]
Firstly congratulations on what is shaping up to be an immense improvement over other similar Proxy services!

I would like to respectfully request the following in order of priority:
1) TorrentDay (Should be very similar setup to IPT as its the same guys)
2) Torrentleech
3) PrivateHD

I am very technically limited but will provide any information you require to help with this request as long as instructions to attain said information is also provided!

Many thanks

**Comment by lxt2** [comment]
1.7.1 has TorrentDay and Torrentleech. Are you able to provide an invite to PrivateHD?

**Comment by theOkinz** [comment]
I can provide you with one if needed.

**Comment by theCheek** [comment]
I'm afraid I don't have any yet! Thanks Okinz for taking care of that :)

**Comment by mmarquezs** [comment]
I did the privatehd one,
https://github.com/cardigann/cardigann/pull/52

**Comment by theCheek** [comment]
awesome! Thank you very much. Now i Just gotta wait for my seedbox to update :(

**Comment by lxt2** [comment]
These are all done! Which seed box are you with @theCheek?

**Comment by theCheek** [comment]
i'm with bytesized @lxt2
