### ISSUE TITLE
Suport for avistaz.to

### ISSUE THREAD

**Issue by gsalva77** [cardigann/cardigann#45]
Is that possible?

Thanks you!!

**Comment by lxt2** [comment]
Will look at it, is it invite only?

**Comment by gsalva77** [comment]
Yeah it is invite only but if you want I can send you an invitation :)

**Comment by mmarquezs** [comment]
I did pull request now: https://github.com/cardigann/cardigann/pull/54

**Comment by gsalva77** [comment]
awesome!

thank you so much!.

2016-10-01 23:10 GMT+09:00 Marc Marquez Santamaria <notifications@github.com
