### ISSUE TITLE
Unable to build at latest stable release in Alpine

### ISSUE THREAD

**Issue by thelamer** [cardigann/cardigann#452]
Hello from Linuxserver.io we are unable to build this project at the latest release in Alpine we get back: 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cardigann@0.0.1 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cardigann@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-11T00_54_14_301Z-debug.log
make: *** [Makefile:29: server/static.go] Error 1
```
From the make setup command. Can you give us any pointers in getting this to build under current Alpine environments, we would also like to bump golang up to 1.11 in Alpine 3.9. We have been holding it back for some time now due to build errors. 

https://github.com/linuxserver/docker-cardigann

**Comment by cactuschibre** [comment]
Do `cd web; npm install` before.
Or add this line do the "Setup" step in the Makefile.

Also, in `web` folder : `yarn install` (yarn must be installed).
