### ISSUE TITLE
No version number when running as a service

### ISSUE THREAD

**Issue by Dnkhatri** [cardigann/cardigann#46]
The cardigann server webpage should mention the installed version. And if possible if a newer version is out.

**Comment by lxt2** [comment]
It does, in the footer. What does the footer on yours say?

**Comment by Dnkhatri** [comment]
Maybe i am missing something here is a screenshot

![screenshot at 2016-10-01 17-46-02](https://cloud.githubusercontent.com/assets/7855682/19013310/c9f00b5c-87ff-11e6-8232-006a8182517f.png)

**Comment by lxt2** [comment]
Interesting, the `dev` bit down the bottom indicates that you are running a development build. How did you install it?

**Comment by Dnkhatri** [comment]
Got the latest version from the equinox download page. The used the
commands that are on the equinox website to install. Then installed and ran
as service.

**Comment by mmarquezs** [comment]
Yeah the same thing in my case it shows like that. Downloaded it following the instructions from here:
https://dl.equinox.io/cardigann/cardigann/stable

```

    wget https://bin.equinox.io/c/3u8U4iwUn6o/cardigann-stable-linux-amd64.tgz
    tar xvf cardigann-stable-linux-amd64.tgz -C /usr/local/bin

```

**Comment by Sek0n** [comment]
Happened to me before as well, only when I ran it as service. It works when ran with the server command.

**Comment by lxt2** [comment]
Ok thanks, I'll check it out. Do you happen to recall which version you downloaded?

**Comment by lxt2** [comment]
Thanks all, perhaps I'm not doing the version tagging correctly in Equinox.

**Comment by lxt2** [comment]
@Sek0n the definitions got bundled in the binary to resolve that point of confusion in 1.7.
