### ISSUE TITLE
No seeders / peers using Pirate bay

### ISSUE THREAD

**Issue by zapp1** [cardigann/cardigann#55]
when using the web search or manual search within sonarr cardigann returning zero seeders and peers for all searches. even when I have checked on the pirate bay and the torrent had multiple seeders/ peers.

Have also tried a few different proxy sites for pirate bay as well

I have had this issue with v1.6.1 and 1.7.0 using a docker install on my qnap nas (ts451Build 4.2.0 and container-station) and a stand-alone Debian server running 8 Jessie

**Comment by lxt2** [comment]
Ah yes, I noticed this yesterday. The issue is that pirate bay returns magnet links, I need to investigate how to figure out seeders and peers for these.

**Comment by lxt2** [comment]
This also applies to eztv I believe.

**Comment by lxt2** [comment]
Fixed.

**Comment by ShadeBlack** [comment]
Sorry to comment on a closed thread, but Is this really fixed?
I'm running cardigann v1.8.0 on win-2008r2 with sonarr v2.0.0.4326
On both Sonarr and manual searching in cardigann, I get 0/0 for every result.
