### ISSUE TITLE
Request support for HDME.eu & BitmeTV.org

### ISSUE THREAD

**Issue by Moenmann** [cardigann/cardigann#56]
Requesting support for HDME.eu & BitmeTV.org. Is this possible? Have invite for HDME.
Thanks :)

**Comment by kaso17** [comment]
please send the invite for HDME to kaso1717 -at- gmail.com. For bitmetv I already have access.

**Comment by lxt2** [comment]
BitMeTV.org is on the list, I don't have access to HDME.eu.

**Comment by kaso17** [comment]
BitMeTV is done.
@Moenmann please check your emails regarding HDME

**Comment by lxt2** [comment]
Many thanks @kaso17!

**Comment by Moenmann** [comment]
You are awesome :)  thanks!
