### ISSUE TITLE
Iptorrents Captcha Failed

### ISSUE THREAD

**Issue by TheCannings** [cardigann/cardigann#59]
Hi,

I have added Iptorrents and added the correct login details but when I come to test it then I get:

An error occurred
Captcha verification failed.please try again!

I have searched around for similiar issues but cannot find anything?

Thanks

Paul

**Comment by aroundmyroom** [comment]
it's very new .. thats why and not everyone has access to such private

**Comment by lxt2** [comment]
Login via the browser, do the captcha, then you will be able to login with cardigann.

**Comment by TheCannings** [comment]
I am running this on a remote server, I have vnc'd into it and logged into iptorrents then tried again and still no joy

**Comment by lxt2** [comment]
Interesting, works fine for me on a remote server. Perhaps we need to move IPTorrents to cookie auth.

**Comment by kreativedev** [comment]
Any progress with this?

**Comment by w33ble** [comment]
Is there a guide for using cookie auth anywhere? I have no idea what to put in that field.

**Comment by TheCannings** [comment]
I asked on glimmer Joe and was given this link that showed me what to do

https://github.com/Jackett/Jackett/wiki/Finding-cookies

**Comment by w33ble** [comment]
Oh, I was trying to copy values out of my parsed cookies. This makes more sense. Thank you!
