### ISSUE TITLE
AlphaRatio not working

### ISSUE THREAD

**Issue by scipio314** [cardigann/cardigann#62]
When testing AlphaRatio I get the response:   

> An error occurred
> Failed to match selector "td:nth-child(5) .time"

**Comment by lxt2** [comment]
Which version?

**Comment by lxt2** [comment]
On master:

```
 ~gopath/s/g/c/cardigann on master ∆ › go run *.go test definitions/alpharatio.yml
Definition file for alpharatio parsed OK ✓
Testing indexer alpharatio
Indexer alpharatio passed ✓
```

**Comment by dbershev** [comment]
I get the same error of 1.8.0 if I click test after the add the tracker in the gui.

**Comment by lxt2** [comment]
I've just pushed up 1.8.1, are you able to try that? I'll put together some troubleshooting steps for you if not.

**Comment by dbershev** [comment]
Well I tried haha..
cardigann@cardigann:/tmp$ cardigann update --channel=edge
INFO[0000] No update available, already at the latest version!

cardigann@cardigann:/tmp$ cardigann update --channel=stable
INFO[0000] No update available, already at the latest version!

**Comment by lxt2** [comment]
Heh, awesome. Hooray for experimental features :)

**Comment by dbershev** [comment]
Where is cardigann installed at? That way I can extract the tar. I've just been using the deb.

**Comment by lxt2** [comment]
The deb will leave the binary in /usr/local/bin/cardigann

**Comment by theCheek** [comment]
FYI I'm on 1.8.0-9-ga1b487c and I can't reproduce this error. Clicking Test works fine for me.

**Comment by scipio314** [comment]
I am on version 1.7.0. I will try updating to see if it goes away.

**Comment by scipio314** [comment]
I updated to verstion 1.8.1-2-g8799858 and the error still occurs when clicking Test.

**Comment by dbershev** [comment]
I also updated to the same version as scipio314 and still got the error. I'm running Ubuntu 16.04.

**Comment by lxt2** [comment]
Able to try the latest?

**Comment by dbershev** [comment]
Same error in 1.8.5-1-g70fa6af unfortunately. Other trackers work, it's just AR.

**Comment by tadfisher** [comment]
Some selectors are off by one. See #91.

**Comment by tadfisher** [comment]
FYI, output on master:

```
cardigann test-definition definitions/alpharatio.yml 
Definition file for alpharatio parsed OK ✓
Testing indexer alpharatio
cardigann: error: Test failed for alpharatio: Failed to match selector "td:nth-child(5) .time", try --help
```

It's possible the search output is formatted differently based on user account state, which would be unfortunate (but could be solvable with some clever negative-index selectors).

**Comment by tadfisher** [comment]
Ah, I've found the culprit. If you set a default filter for your account, the empty column at the beginning of the row is removed. You can reproduce this by appending `&searchsubmit=1` to the search URL.

I'd suggest appending that by default, so the output is normalized regardless of default filter settings. Additionally, appending "filter_cat[n]" parameters is necessary to override the user's default filter.

**Comment by mmarquezs** [comment]
I'm getting this now on edge branch version 1.8.5-18-g8437de7.
I checked alpharatio and I don't have a default filter set and even if I had it this last pull request should have fixed that. So something changed.

**Comment by ldexterldesign** [comment]
Hey,

Thanks for software

Unable to get https://alpharatio.cc/ working either

Let me know if you have any issues - happy to help

Hope to hear back

Regards

**Comment by ldexterldesign** [comment]
Follow up

Working now - who knows why before?

Regards

**Comment by wasgehthierab** [comment]
I discovered that https is not working - http is working with no problem.
