### ISSUE TITLE
EZTV and TPB not returning seed/peers and magnet not working

### ISSUE THREAD

**Issue by thatvalis** [cardigann/cardigann#63]
Hi,

Managed to get it running with the following command:
cardigann server --bind 127.0.0.1 --port XXXX
Is that the proper way to start the server in the foreground?
Anyway, I can access localhost:XXXX configuring it like this.

And it seems to add trackers fine, and when I test them it also seems to work fine.
But when I try the search function it returns search findings with 0/0 in seeds/peers.
And when I try to add a torrent to my torrent client it fails.

Now it's not working at all, saying: "An error occurred, Expected no results, got 5" when i Test the trackers.

How do I get it working?

**Comment by thatvalis** [comment]
Returns: 
Get magnet://?xt=urn:btih:.............unsupported protocol scheme "magnet"

When I try to add a search result.

**Comment by lxt2** [comment]
Did you read https://github.com/cardigann/cardigann#installation ?

**Comment by lxt2** [comment]
Also, what version are you using?

**Comment by thatvalis** [comment]
Yes I have read it several times to see if I missed something.
I'm on Windows 10, as I understand I only need to download the .exe file from equinox and then run it with CMD.
I am using the latest stable version.
