### ISSUE TITLE
Bad Gateway error from Couchpotato

### ISSUE THREAD

**Issue by theCheek** [cardigann/cardigann#66]
In Jackett there are two links provided for each indexer - one for use in Sonarr and the other for Couchpotato. However in Jackett there's only one - so I'm assuming I'm not being n00bish with this report, and have entered the same url for couchpotato's torrentpotato section.

If this is correct, theres an issue with couchpotato not being able to open the cardigann url, with error:

> TTPError: 502 Server Error: Bad Gateway for url: http://my.server.me:44795/torznab/alpharatio?imdbid=tt_replacedId_&search=movie+name&user=&passkey=xxx[0m

After a while, couchpotato gives up and starts ignoring cardigann completely.

Attaching the couchpotato log of the errors. Also where do I find the cardigann logs on an ubuntu setup?
[couchpotatoError.txt](https://github.com/cardigann/cardigann/files/507852/couchpotatoError.txt)

**Comment by lxt2** [comment]
I need to update the docs, I haven't added support for couchpotato yet.

**Comment by theCheek** [comment]
Ah that would explain it then :) Many thanks.

**Comment by lxt2** [comment]
Closing in favor of #67
