### ISSUE TITLE
TV serie mapping ?

### ISSUE THREAD

**Issue by aroundmyroom** [cardigann/cardigann#71]
Timeless 2016 S01E01
cannot be found cause it's not uploaded as Timeless 2016 but as Timeless S01E01
Sonarr gives Timeless (2016) but some series are not uploaded that way than it cannot find the show

Maybe there should be an option to add / remove the 'year' from the search

**Comment by kaso17** [comment]
While I have the same problem doing this in cardigann is the wrong approach for me.
I'm not sure if adding it as alternative name to http://thexem.de/ might work (It's use by sonarr already).
In case future timeless releases won't be properly tagged with 2016 I'll look into this and fix it on the sonarr side. You might want to open a sonarr issue for this articular case, there might be already a workaround.

**Comment by aroundmyroom** [comment]
I think issue has been resolved within the tracker(s). I see now that the latest releases are properly tagged and named. 1st HDTV was not. Ok for not solving or adding feature.
