### ISSUE TITLE
Issues with speed.cd (seeders/peers) appended to title

### ISSUE THREAD

**Issue by subzero79** [cardigann/cardigann#72]
The tracker speed.cd is returning the title with the number of seeders/peers appended to it. Is a very strange issue.

The debug log is here using version 1.8.1-2-g8799858 

https://gist.github.com/subzero79/8260b4c9c810339036f9ad3ec4bd6d0e

Here is the screenshot also of the UI search

![screen shot 2016-10-05 at 7 10 33 am](https://cloud.githubusercontent.com/assets/7058119/19092623/e124d424-8aca-11e6-897b-86546683fd00.png)

**Comment by kaso17** [comment]
Can you sent an invite to kaso1717 -at- gmail.com so I can debug it?

**Comment by subzero79** [comment]
No sorry i can't. I had one invite last year an it went with the original jackett developer.

**Comment by subzero79** [comment]
Ok I've changed selector now to 

```selector:  td.lft > div > a > b```

is working now. I've created PR so we can close here
