### ISSUE TITLE
Issue with magnet links not working

### ISSUE THREAD

**Issue by zapp1** [cardigann/cardigann#78]
Magnet Links not formatted correctly (at least for transmission)

When I try and use a magnet link from cardigann transmission will not add it as a torrent. When I inspect the magnet link path cardigann always starts;

magnet://?xt=urn:btih:<rest of link>

removing the // and then pasting the whole link into transmission correctly allows the magnet link to work.

**Comment by lxt2** [comment]
Yup, you are right.

**Comment by lxt2** [comment]
This is now fixed in master. It will go out in the next stable release, or you can grab it from the edge channel. https://dl.equinox.io/cardigann/cardigann/edge
