### ISSUE TITLE
Still No seeders / peers using Pirate bay

### ISSUE THREAD

**Issue by zapp1** [cardigann/cardigann#79]
RE#55 (No seeders / peers using Pirate bay) Sorry if I have not done this properly but I was unable to open the original issue.

I'm still not seeing seeders or peers when I search with TPB. I thought it may be because my ISP blocks TPB but I have set up a test on another ISP that does not block the site and still the same issue.

I have updated to the latest version on both systems and still no joy I'm using a docker container and a stand-alone server to run cardigann using Debian but I also see from other pots that it's effecting some windows users as well.

As I don't have access to any of the privet trackers I cannot test to see if this just a TPB issue or more general.

**Comment by lxt2** [comment]
Could you confirm exactly what version you have please?

**Comment by lxt2** [comment]
it was fixed in 1.8.2. https://github.com/cardigann/cardigann/commit/52594874e7194d62bf4f994883c95e96d6f6c644

**Comment by zapp1** [comment]
Hi I was using that version I have just updated to 1.8.3 and still the same issue also when i do a manual search in sonarr I get the following, as you can see the age of the file is not right not sue if that is part of the same issue

![cardigann](https://cloud.githubusercontent.com/assets/22563599/19153306/e3da0f1e-8bcd-11e6-8953-ec1d4be5feaf.png)

**Comment by lxt2** [comment]
Are you able to reproduce the incorrect peer count when doing a manual search in Cardigann @zapp1?

**Comment by zductiv** [comment]
I'm also on 1.8.3 and can confirm incorrect peer count when doing manual search in Cardigann.

Also, do note the date of the torrent on zapps comment

![image](https://cloud.githubusercontent.com/assets/8939440/19177252/e871a42c-8c79-11e6-8e07-ac9d0986d95a.png)

**Comment by lxt2** [comment]
I'm sure you must have an out of date definition @zductiv. Oh! I bet I know what is happening, I bet somewhere you have the old definitions in the filesystem from before we started bundling them into the binary. Could you look for a `definitions/` dir in the working dir of your cardigann binary?

**Comment by zductiv** [comment]
I only started with Cardigann with the binary release v1.8.0. In the folder that I put the cardigann.exe the only other file is cardigann.exe.old from doing a cardigann update from the command prompt.

%appdata%\roaming\cardigann only has config.json.

Not sure if cardigann creates files elsewhere that I should be looking for.

**Comment by lxt2** [comment]
The latest version on edge will show you where the definition was loaded from if you click on the name in the list:

![](http://i.imgur.com/l7uoUKG.png)

**Comment by lxt2** [comment]
![](http://i.imgur.com/9Y85Fyf.png) 
![](http://i.imgur.com/bdC1dQm.png)

**Comment by zductiv** [comment]
Updated to 1.8.5-1-g70fa6af.

The Pirate Bay returns builtin:/definitions/thepiratebay.yml and the cardigann search function is returning the correct number of peers now.

When added to Sonarr, the cardigann TPB index is returning the correct number of peers also.

**Comment by zapp1** [comment]
I can also confirm that after updating to 1.8.5 that this has resolved my issue in both the cardigan web app and sonarr.

Thanks

**Comment by Githubtordl** [comment]
Yep, it's fixed for me as well on 1.8.5

**Comment by lxt2** [comment]
🙌🏻
