### ISSUE TITLE
How to setup password in config.json?

### ISSUE THREAD

**Issue by W0oper** [cardigann/cardigann#83]
I'm trying to setup a password in config.json, but can't do it. Can anyone explain please, how to set "global.password" in the config.json file?

**Comment by Sek0n** [comment]
find the "global" line in config.json, and under it add it like below:

```
"global": {
    "apikey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "passphrase": "xxxxxxxxx"
}
```

**Comment by W0oper** [comment]
Thanks!

**Comment by W0oper** [comment]
Hmm. I get "ERRO[0000] invalid character '"' after object key:value pair"

**Comment by Sek0n** [comment]
Can you paste the config?

Be sure to remove any login/pass info first.

**Comment by W0oper** [comment]
```
{
  "global": {
    "apikey": "xxxx",
    "passphrase": "xxxx"
  },
```

Forgot the ",". But now, cardigann isn't asking me for a password. When i start the application with cardigann server --passphrase xxx it's working, but with passphrase in config.json and cardigann service start it's not. Any ideas?

**Comment by Sek0n** [comment]
It looks good. Maybe it kept you signed in from when you had --passphrase running. Could check that with another browser, or delete the cookies/cache for the site.

**Comment by W0oper** [comment]
Tested it with Chrome (default browser), Firefox and Safari - cleared the cache - still not asking for a password. :/

**Comment by Sek0n** [comment]
Hm, I'm not sure then. Are you on the latest release? I think 1.7.3 or so was when it started looking for the pass in the config file.

**Comment by W0oper** [comment]
Yep, i'm on 1.8.5. Maybe a developer can check this issue out.

**Comment by lxt2** [comment]
Delete `apikey`, it's derived from `passphrase`.

**Comment by lxt2** [comment]
The function that gets the shared key is here https://github.com/cardigann/cardigann/blob/master/server/auth.go#L82

**Comment by W0oper** [comment]
My config looks like this right now:

`"global": {
    "passphrase": "mypassword"
  },`

Restartet cardigann, still without asking for a password.

**Comment by lxt2** [comment]
Hrm, strange. When I do the same, I see the following log messages:

```
DEBU[0011] Authenticating request                        method=header
INFO[0011] Incorrect api key "xxx", expected xxx 
```

and I am prompted for a password, which if I provide the new one, works correctly. 

Could you start with `--debug` and check for similar messages? It's also possible that a different config file is being used to the one you think, debug output will also list that.

**Comment by W0oper** [comment]
Interesting. When i start cardigann with "cardigann server", the script is asking for a password. When i start it with sudo cardigann service start it's not. Maybe something wrong with the upstart script?

**Comment by lxt2** [comment]
It's possible, you could test running as a service by running it interactively with: `cardigann service --debug run`. 

I'll do some digging and see if I can narrow down the problem. You are using upstart and not systemd, right?

**Comment by W0oper** [comment]
With cardigann service --debug run it's asking for a password, without not. Log:

`DEBU[0000] Running service action run on platform linux-upstart. 
I: 14:47:16 Running interactively
I: 14:47:16 Running service via linux-upstart.
I: 14:47:16 Reading config {"path":"/home/owner/.config/cardigann/config.json"}
I: 14:47:16 Cardigann 1.8.5 {}
I: 14:47:16 Config path is /home/owner/.config/cardigann/config.json {}
I: 14:47:16 Cache dir is /home/owner/.cache/cardigann {}
I: 14:47:16 Found 22 built-in definitions {}
I: 14:47:16 Found 1 indexers enabled via config {}
I: 14:47:16 Listening on 0.0.0.0:5060 {}
I: 14:47:25 GET / {"method":"GET","path":"/","remote":"xxxx"}
I: 14:47:25 GET /static/css/main.fbe2e7fd.css {"method":"GET","path":"/static/css/main.fbe2e7fd.css","remote":"xxxxx"}
I: 14:47:25 GET /static/js/main.76f69f86.js {"method":"GET","path":"/static/js/main.76f69f86.js","remote":"xxxxx"}
I: 14:47:26 GET /xhr/auth {"method":"GET","path":"/xhr/auth","remote":"192.164.148.155:49358"}
I: 14:47:26 GET /xhr/version {"method":"GET","path":"/xhr/version","remote":xxxx"}
I: 14:47:26 Authenticating request {"method":"header"}
I: 14:47:26 Incorrect api key "null", expected xxxxxx {}
I: 14:47:26 GET /favicon.ico {"method":"GET","path":"/favicon.ico","remote":"xxxxx"}`

**Comment by lxt2** [comment]
That's very bizarre. I bet the non-interactive service version is loading a config file from somewhere different. By default it will be running as root, so perhaps it's either in `/.config/cardigann/config.json` or `/root/.config/cardigann/config.json`?

Failing that, is it possible to post what the service definition that was installed looks like? That might help us narrow it down.

**Comment by W0oper** [comment]
Config file was in /.config, if started via sudo cardigann service start - i added the passphrase in this file and now it's working. Maybe this should be stated in the readme file or elsewhere to help other users.

Thanks for your help!
