### ISSUE TITLE
No Labels For Text Fields

### ISSUE THREAD

**Issue by mcowger** [cardigann/cardigann#84]
I'm seeing no labels for text fields in Cardigann for any tracks except for host names, so I'm not sure what to put in there:

![image](https://cloud.githubusercontent.com/assets/1929548/19206389/729af946-8c9d-11e6-8aae-fd0de35c24fb.png)

Have cleared browser cache and tried multiple browsers.  Tried stable and edge branches.  Disabled adblocking

**Comment by mcowger** [comment]
Here's the debug output from the server when pulling up the above:

```
DEBU[0063] GET /xhr/indexers/torrentday/config           method=GET path=/xhr/indexers/torrentday/config remote=67.169.61.241:51995
DEBU[0063] Authenticating request                        method=header
DEBU[0063] No url found for indexer                      indexer=torrentday
DEBU[0063] Loaded indexer                                indexer=torrentday
DEBU[0063] Loaded indexer info                           info={ID:torrentday Title:TorrentDay Description: Link:http://td-update.com/ Language:en-us Category:}
DEBU[0063] Getting indexer config                        config=map[url:http://td-update.com/] indexer=torrentday
```

**Comment by lxt2** [comment]
Ooops! This was a regression in the latest version.

**Comment by lxt2** [comment]
Will shortly be available in the edge build and in the next release. Thanks for the report.
