### ISSUE TITLE
Bug report: Base Url config not used

### ISSUE THREAD

**Issue by mmarquezs** [cardigann/cardigann#90]
### Issue experienced

I tried to change the base url, so I can easily make it work with a reverse proxy but it doesn't seems to work. 
### Steps to reproduce

I changed the config.json, the global part  :

```
  "global": {
    "apikey": "API",
    "baseurl": "/cardigann"
  },
```

(I also tried "cardigann" and "/cardigann/")

After that I restarted the service but it seems it doesn't use that setting or maybe I'm setting it wrong. 
### Cardigann version (in the footer, or via `cardigann --version`)

1.8.5

**Comment by lxt2** [comment]
Interesting, what made you think that there was a base url config? It's something I'd be happy to add, but it doesn't exist at the minute. The XHR requests that the javascript side makes to the server side might present some problems too, but shouldn't be too bad.

**Comment by mmarquezs** [comment]
Well it's a common feature to have sonarr,couchpotato,jacket,.. have it and I saw here baseurl together with apikey and passphrase and I tought it had the config ( I didn't look  a lot on the code obviously):

https://github.com/cardigann/cardigann/blob/master/server/handler.go

**Comment by lxt2** [comment]
Good point, it does look like I implemented part of it :)

**Comment by Ciiss0u** [comment]
Yeah it will be perfect if implemented, 

I use some nginx revese proxy in subdirs of my "dl" site (/sonarr; /couchpotato ; etc...) and It's mandatory for me to have this option to no have to create an other site only for cardigann...

Thanks 👍

**Comment by onedr0p** [comment]
Please add this :)

**Comment by kkuhle** [comment]
It would be great to see this implemented!

**Comment by tdharris** [comment]
I would really love to see this implemented! It would be perfect!

**Comment by JoeStratton** [comment]
I would like this as well!

**Comment by exofudge** [comment]
Is there any progress on this?

**Comment by kilroy83** [comment]
Yes, if you can add that. it will be perfect ;)

**Comment by lxt2** [comment]
I added this recently, you can use `cardigann server --prefix /blah`

**Comment by teotikalki** [comment]
What about the respecting the baseurl directive? The '--prefix' flag is great and all but isn't ideal for configuration as a service.
