### ISSUE TITLE
EZTV parsing and searching issues

### ISSUE THREAD

**Issue by noahbody-knows** [cardigann/cardigann#95]
The EZTV definition has multiple searching and parsing issues; here are the ones I've found so far:

* The field definitions for seeders needs to strip commas (which are being used as thousands separators), and replace '-' with '0' (sometimes the seeder count is a '-')
* Release dates are relative, in the form "2 mo" or "3 years" - the years seem to be parsed correctly, but not the "mo"
* EZTV always returns search results, even if a query fails: you will instead get 50 irrelevant results
* EZTV series years don't always work correctly with Sonarr: if Sonarr tags the series with a year but EZTV does not (e.g. Sonarr uses "King 2011" but EZTV just lists episodes as "King"), then EZTV will fail *all* queries for that series and return 50 irrelevant results (because it doesn't have any episodes that match "King 2011").  A possible workaround would be to exclude series years from the query string sent to EZTV, thereby broadening the match.  (Or perhaps to replace only specific problematic series' query strings?)

I have the impression that most of these things could probably be fixed at the definition level with appropriate filters and query string formation, but there isn't a lot of documentation on that yet.  I've managed to reverse engineer a *bit* of how some of the definition stuff works, but not enough to pull off the query string modification.  (Otherwise, I'd send a pull request rather than a bug report.)  Thanks.

**Comment by lxt2** [comment]
Thanks for the detailed bug report. Indexer definition docs are definitely a big TODO. 

I'll address the first two points as core fixes. Sounds like point 3 is unavoidable?

I'll have a think about the best way to handle years being appended. Might be worth fixing in core as it will crop up again.

**Comment by noahbody-knows** [comment]
The real issue, I think, behind items 3 and 4 is that EZTV (and similar systems such as ShowRSS) is not really intended as a search engine.  Instead, it is a catalog of [shows](https://eztv.ag/showlist/) with lists of available torrents for those shows.  Ideally, for systems like this there would be a way to search the show list rather than using the site's own search.  In the case of both EZTV and ShowRSS, there is a page that can be parsed to get a show list, and from that data a URL can be formulated to retrieve a list of torrents for a show.  Perhaps a "browse" configuration to specify selectors to find shows, plus a template for creating a URL from the extracted data for a show?

(Since EZTV *does* have tvrage and tvmaze identifiers on its show pages, it's potentially possible to match the shows without doing "search" at all, by supporting the appropriate torznab capability flags.  The downside is that each individual show page would have to be scraped and cached to map the IDs, since EZTV's "search" doesn't support it.)

Also, EZTV has full data for a torrent (seed, peers, properly-formatted release date) on its individual "episode" pages, which are linked from both the search and browse pages.  So having the ability to follow those links as part of such a "browse search" would be handy.

Of course, it's possible that there is just no way to make EZTV sane.  Or perhaps a Sonarr plugin for EZTV would make more sense.  But being able to code this in YAML beats the heck out of C#.  :)

**Comment by lxt2** [comment]
The torznab protocol actually makes it possible for shows to be requested by tvrage ID. At present we're not exposing that as a capability, but we certainly could. The issue is when you try and get into fuzzy matching show names, for instance "The Valley" vs "Silicon Valley", especially when you are trying to parse show names out of HTML or filenames. I will investigate EZTV a bit more, if it's possible to query by tvrage identifiers, that would be awesome.

**Comment by lxt2** [comment]
Just realized you said a lot of what I said in the middle paragraph :) That will teach me to reply before properly digesting.

**Comment by noahbody-knows** [comment]
Unfortunately EZTV doesn't *search* by tvrage or tvmaze identifiers, and some shows are listed with one ID, some by the other.  I found another site that can search shows by IMDB id, though: http://eztvtorrent.com/ -- searching for ttNNNNNNN identifiers seems to work to find a show.  

The main challenge with it is that you have to extract episode info (SnnEnn) from magnet links, and once you search for the IMDB id, you have to then load the actual show page.

(Well, and of course that the torznab API doesn't do imdb titles, I don't think.  :( And eztvtorrent doesn't search by any other ID, even though it *has* the TVDB identifiers as well.  I suppose one could use tvdb to convert the tvdb id to an imdb id, but at that point things are getting pretty silly and the definitions .yaml will be practically Turing-complete...)

**Comment by lxt2** [comment]
What I can do fairly easily is to add a config option for indexers to either use the `Title` format or `TitleWithoutYear` format.

**Comment by lxt2** [comment]
I'm working on doing some better parsing of results, at which point it should be easier to filter out the junk, although sonarr does it anyway eventually.

**Comment by noahbody-knows** [comment]
On a semi-unrelated note, I've noticed that there is an "EZTV API" of sorts used by Popcorn Time: multiple sites with a static JSON interface: https://www.reddit.com/r/PopCornTime/comments/4943sk/apis_list/

Basically sites that follow this API publish pages like `/shows/1`, `/shows/2`, etc. which are a paged list of JSON structs with show IDs and other data like IMDB and tvdb ids.  There are then `/show/ttNNNNNNN`  pages with the episode and torrent lists in JSON.

This probably doesn't fit into Cardigann's selector-oriented model (not to mention still needing a two-stage search), but it seems like something it'd be good to have a torznab adapter for: the fact that PT uses this API means that sites providing it will be around for a long time, and that it's a fairly *stable* API as well.

**Comment by lxt2** [comment]
Wow, that's really interesting. I'll definitely look at that.

**Comment by lxt2** [comment]
I'm working on a branch that uses the [releaseinfo](https://github.com/cardigann/releaseinfo) library I recently ported from sonarr: 

https://github.com/cardigann/cardigann/tree/releaseinfo

It filters results by the season requested, so excludes the spurious EZTV results. Have had really good results from this so far, any thoughts on approach @noahbody-knows?

**Comment by noahbody-knows** [comment]
Dunno, don't know enough .go and haven't built it before; I've been pulling docker images to run it, so I'll happily give it a shot if there's a tag I can `docker pull`...  But certainly the approach of making sure the series name is actually in there makes sense.

**Comment by lxt2** [comment]
The above feature should be in master and will shortly be part of 1.9. Thanks for your help!

**Comment by lxt2** [comment]
Well, this is slight progress anyway:

![screenshot](http://i.imgur.com/XiVHrc2.png)

**Comment by noahbody-knows** [comment]
I just pulled the latest from docker (which identifies itself as "v1.8.7-43-g72447b0", not 1.9), and it still has the problem, unless I'm missing some secret config option on either Sonarr or Cardigann?

**Comment by noahbody-knows** [comment]
Still can't get this to work with 1.9.2, either.  I re-added the definition in cardigann and re-added the indexer in Sonarr, still get a big stack of matches for the wrong series(es), including for the example you show working above.  What am I missing?
